use_frameworks!

platform :tvos, '13.0'

target 'UIFocusHelper_Example' do
  pod 'UIFocusHelper', :path => '../'
  pod 'tvOSShelfController', '0.1.9'
  target 'UIFocusHelper_Tests' do
    inherit! :search_paths

    
  end
end
