//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable, NSString, NSTimer, UIScrollView, _UIFocusEnginePanGestureRecognizer, _UIFocusFastScrollingTouchSequence, _UIRotaryGestureRecognizer;
@protocol _UIFocusFastScrollingRecognizerDelegate;

__attribute__((visibility("hidden")))
@interface _UIFocusFastScrollingRecognizer : NSObject
{
    _UIFocusEnginePanGestureRecognizer *_panGesture;	// 8 = 0x8
    _UIRotaryGestureRecognizer *_rotaryGesture;	// 16 = 0x10
    _UIFocusFastScrollingTouchSequence *_currentTouch;	// 24 = 0x18
    NSMapTable *_swipeSequences;	// 32 = 0x20
    NSTimer *_swipeIntervalTimer;	// 40 = 0x28
    UIScrollView *_previewingScrollView;	// 48 = 0x30
    NSTimer *_previewingTouchTimer;	// 56 = 0x38
    unsigned long long _spatialFocusUpdateCount;	// 64 = 0x40
    _Bool _persistFastScrollingPreviewThroughReset;	// 72 = 0x48
    _Bool _enabled;	// 73 = 0x49
    id <_UIFocusFastScrollingRecognizerDelegate> _delegate;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x0000000000666aef
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <_UIFocusFastScrollingRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)focusEnginePanGesture:(id)arg1 touchCancelledAtDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x0000000000666a72
- (void)focusEnginePanGesture:(id)arg1 touchEndedAtDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x0000000000666a25
- (void)focusEnginePanGesture:(id)arg1 touchMovedToDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x00000000006669bc
- (void)focusEnginePanGesture:(id)arg1 touchBeganAtDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x0000000000666953
- (void)_deactivatePreviewingScrollViewIfNecessary;	// IMP=0x00000000006668eb
- (void)_activatePreviewingScrollViewForScrollingStyle:(long long)arg1 emphasisAnimation:(_Bool)arg2 overrideIndexDisplayMode:(_Bool)arg3;	// IMP=0x000000000066682f
- (void)_activatePreviewingScrollViewForEdgeGesture;	// IMP=0x0000000000666813
- (void)_activatePreviewingScrollViewForEdgeGestureAfterDelay;	// IMP=0x00000000006667b1
- (void)_notifyDelegateWithScrollView:(id)arg1 scrollingStyle:(long long)arg2 heading:(unsigned long long)arg3;	// IMP=0x000000000066669d
- (_Bool)_scrollViewIsEligibleForFastScrolling:(id)arg1 alongHeading:(unsigned long long)arg2 withScrollingStyle:(long long)arg3;	// IMP=0x00000000006664ee
- (id)_scrollViewsContainingCurrentlyFocusedItem;	// IMP=0x00000000006661a5
- (_Bool)_attemptToImmediatelyRecognizeEdgeGesture;	// IMP=0x0000000000665fd9
- (id)_deepestEligibleScrollViewContainingFocusedItem:(unsigned long long)arg1 withScrollingStyle:(long long)arg2;	// IMP=0x0000000000665e41
- (_Bool)_canFastScrollWithEdgeSwipe;	// IMP=0x0000000000665dd9
- (_Bool)_swipeSequenceCanBeginFastScrolling:(id)arg1;	// IMP=0x0000000000665d89
- (void)_updateActiveSwipeSequencesForScrollViews:(id)arg1;	// IMP=0x0000000000665973
- (unsigned long long)_bestHeadingForAccumulator:(struct CGVector)arg1;	// IMP=0x0000000000665812
- (void)_swipeIntervalElapsed:(id)arg1;	// IMP=0x0000000000665800
- (void)_stopSwipeIntervalTimer;	// IMP=0x00000000006657cf
- (void)_startSwipeIntervalTimer;	// IMP=0x00000000006656f9
- (void)_swipeOccuredAlongHeading:(unsigned long long)arg1;	// IMP=0x0000000000664f86
- (void)_touchSequenceDidEnd:(id)arg1;	// IMP=0x0000000000664dcf
- (void)reset;	// IMP=0x0000000000664bf0
- (void)_handlePanGesture:(id)arg1;	// IMP=0x00000000006647d3
- (_Bool)attemptToImmediatelyRecognizeRotaryGesture;	// IMP=0x00000000006646a6
- (_Bool)canImmediatelyRecognizeRotaryGesture;	// IMP=0x0000000000664669
- (void)deactivateRotaryGesturePreviewingScrollViewIfNecessary;	// IMP=0x0000000000664653
- (void)activateRotaryGesturePreviewingScrollViewWithEmphasisAnimation:(_Bool)arg1;	// IMP=0x0000000000664630
- (void)pageButtonPressWithHeading:(unsigned long long)arg1 didRepeat:(unsigned long long)arg2;	// IMP=0x00000000006645c0
- (void)joystickMovementWithHeading:(unsigned long long)arg1 didRepeat:(unsigned long long)arg2;	// IMP=0x0000000000664541
- (void)directionalPressWithHeading:(unsigned long long)arg1 didRepeat:(unsigned long long)arg2;	// IMP=0x0000000000664490
- (void)_focusDidUpate:(id)arg1;	// IMP=0x000000000066414a
- (void)dealloc;	// IMP=0x000000000066409a
- (id)initWithPanGesture:(id)arg1 rotaryGesture:(id)arg2;	// IMP=0x000000000066403b
- (id)initWithPanGesture:(id)arg1;	// IMP=0x0000000000663f3f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

