//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, UIImage, UIView, _UIFocusRegionMapSnapshotRequest;

__attribute__((visibility("hidden")))
@interface _UIFocusRegionMapSnapshot : NSObject
{
    _Bool _isFocusedRectEmpty;	// 8 = 0x8
    _Bool _didSetRegionClipFrame;	// 9 = 0x9
    struct CGRect _regionClipFrame;	// 16 = 0x10
    _Bool _committed;	// 48 = 0x30
    _Bool _privateSnaphot;	// 49 = 0x31
    _Bool _clipToSnapshotRect;	// 50 = 0x32
    UIImage *_visualRepresentation;	// 56 = 0x38
    _UIFocusRegionMapSnapshotRequest *_request;	// 64 = 0x40
    UIView *_rootView;	// 72 = 0x48
    NSArray *_sortedFocusContainerGuideMapEntries;	// 80 = 0x50
    NSMutableArray *_detectedFocusableViewMapEntries;	// 88 = 0x58
    NSMutableArray *_detectedFocusableGuideMapEntries;	// 96 = 0x60
    NSMutableArray *_detectedFocusContainerGuideMapEntries;	// 104 = 0x68
    NSMutableArray *_retainedPromiseRegions;	// 112 = 0x70
    unsigned long long _focusHeading;	// 120 = 0x78
    UIView *_focusableRegionAncestorView;	// 128 = 0x80
    NSArray *_finalFocusableRegionMapEntries;	// 136 = 0x88
    struct CGPoint _visualRepresentationScreenCenter;	// 144 = 0x90
    struct CGRect _mapEntriesFrame;	// 160 = 0xa0
    struct CGRect _snapshottedRect;	// 192 = 0xc0
    struct CGRect _focusedRect;	// 224 = 0xe0
    struct CGRect _visualRepresentationMinimumArea;	// 256 = 0x100
}

+ (id)combinedVisualRepresentationForSnapshots:(id)arg1 scaleFactor:(double)arg2;	// IMP=0x001000000062b313
- (void).cxx_destruct;	// IMP=0x000000000062c21a
@property(copy, nonatomic) NSArray *finalFocusableRegionMapEntries; // @synthesize finalFocusableRegionMapEntries=_finalFocusableRegionMapEntries;
@property(nonatomic) struct CGPoint visualRepresentationScreenCenter; // @synthesize visualRepresentationScreenCenter=_visualRepresentationScreenCenter;
@property(nonatomic) __weak UIView *focusableRegionAncestorView; // @synthesize focusableRegionAncestorView=_focusableRegionAncestorView;
@property(nonatomic) struct CGRect visualRepresentationMinimumArea; // @synthesize visualRepresentationMinimumArea=_visualRepresentationMinimumArea;
@property(nonatomic) _Bool clipToSnapshotRect; // @synthesize clipToSnapshotRect=_clipToSnapshotRect;
@property(nonatomic) unsigned long long focusHeading; // @synthesize focusHeading=_focusHeading;
@property(nonatomic) struct CGRect focusedRect; // @synthesize focusedRect=_focusedRect;
@property(retain, nonatomic) NSMutableArray *retainedPromiseRegions; // @synthesize retainedPromiseRegions=_retainedPromiseRegions;
@property(retain, nonatomic) NSMutableArray *detectedFocusContainerGuideMapEntries; // @synthesize detectedFocusContainerGuideMapEntries=_detectedFocusContainerGuideMapEntries;
@property(retain, nonatomic) NSMutableArray *detectedFocusableGuideMapEntries; // @synthesize detectedFocusableGuideMapEntries=_detectedFocusableGuideMapEntries;
@property(retain, nonatomic) NSMutableArray *detectedFocusableViewMapEntries; // @synthesize detectedFocusableViewMapEntries=_detectedFocusableViewMapEntries;
@property(copy, nonatomic) NSArray *sortedFocusContainerGuideMapEntries; // @synthesize sortedFocusContainerGuideMapEntries=_sortedFocusContainerGuideMapEntries;
@property(nonatomic, getter=isPrivateSnapshot) _Bool privateSnaphot; // @synthesize privateSnaphot=_privateSnaphot;
@property(nonatomic, getter=isCommitted) _Bool committed; // @synthesize committed=_committed;
@property(readonly, nonatomic) struct CGRect snapshottedRect; // @synthesize snapshottedRect=_snapshottedRect;
@property(readonly, nonatomic) __weak UIView *rootView; // @synthesize rootView=_rootView;
@property(readonly, copy, nonatomic) _UIFocusRegionMapSnapshotRequest *request; // @synthesize request=_request;
- (id)debugQuickLookObject;	// IMP=0x000000000062c034
- (id)visualRepresentationWithMinimumArea:(struct CGRect)arg1;	// IMP=0x000000000062a061
@property(readonly, nonatomic) UIImage *visualRepresentation; // @synthesize visualRepresentation=_visualRepresentation;
@property(readonly, nonatomic) struct CGRect mapEntriesFrame; // @synthesize mapEntriesFrame=_mapEntriesFrame;
- (void)_didChooseFocusCandidateRegion:(id)arg1;	// IMP=0x00000000006297cf
- (id)_snapshotByFulfillingPromiseFocusRegionEntry:(id)arg1;	// IMP=0x0000000000628baf
- (id)focusableRegionMapEntriesLimitedByFocusContainerGuide:(id)arg1;	// IMP=0x0000000000628841
@property(readonly, copy, nonatomic) NSArray *allFocusableRegionMapEntries;
- (void)_commit;	// IMP=0x00000000006287ef
- (void)_updateSortedFocusContainerGuideMapEntries;	// IMP=0x000000000062877e
- (void)_updateFinalFocusableRegionMapEntries;	// IMP=0x00000000006286e4
- (id)_sortedEligibleFocusContainerGuidesInArray:(id)arg1;	// IMP=0x0000000000627d6e
- (id)_finalFocusableRegionMapEntriesFromViewMapEntries:(id)arg1 guideMapEntries:(id)arg2;	// IMP=0x0000000000627a79
- (id)_finalFocusableRegionMapEntriesFromMapEntries:(id)arg1;	// IMP=0x000000000062745f
- (void)_punchHoleInMap:(id)arg1 atFrame:(struct CGRect)arg2;	// IMP=0x00000000006271ca
- (void)_occludeFocusInFrame:(struct CGRect)arg1;	// IMP=0x00000000006270e3
- (void)_addFocusContainerGuide:(id)arg1 withFrame:(struct CGRect)arg2;	// IMP=0x0000000000626f88
- (void)_addFocusableRegion:(id)arg1 isFocusGuide:(_Bool)arg2 withFrame:(struct CGRect)arg3;	// IMP=0x0000000000626ccd
- (struct CGRect)_clippedRegionFrame:(struct CGRect)arg1 isFocusGuide:(_Bool)arg2;	// IMP=0x0000000000626abc
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000000626887
- (id)_initWithRequest:(id)arg1;	// IMP=0x00000000006265ac

@end

