//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIView.h"

@class NSArray, NSMutableArray, UIFont;

__attribute__((visibility("hidden")))
@interface _UIFocusFastScrollingIndexBarView : UIView
{
    UIView *_indicatorView;	// 8 = 0x8
    double _preferredIndicatorWidth;	// 16 = 0x10
    double _preferredLabelFontSize;	// 24 = 0x18
    NSMutableArray *_backgroundLabels;	// 32 = 0x20
    NSMutableArray *_foregroundLabels;	// 40 = 0x28
    UIView *_foregroundWrapperView;	// 48 = 0x30
    UIView *_foregroundMaskView;	// 56 = 0x38
    long long _deflectedIndex;	// 64 = 0x40
    double _deflectionAmount;	// 72 = 0x48
    UIFont *_backgroundFont;	// 80 = 0x50
    UIFont *_foregroundFont;	// 88 = 0x58
    UIView *_emphasisBackgroundView;	// 96 = 0x60
    NSArray *_entries;	// 104 = 0x68
    long long _focusProminence;	// 112 = 0x70
    long long _style;	// 120 = 0x78
    struct CGPoint _minimumContentOffset;	// 128 = 0x80
    struct CGPoint _maximumContentOffset;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x0000000000663d7f
@property(nonatomic) long long style; // @synthesize style=_style;
@property(nonatomic) struct CGPoint maximumContentOffset; // @synthesize maximumContentOffset=_maximumContentOffset;
@property(nonatomic) struct CGPoint minimumContentOffset; // @synthesize minimumContentOffset=_minimumContentOffset;
@property(nonatomic) long long focusProminence; // @synthesize focusProminence=_focusProminence;
@property(copy, nonatomic) NSArray *entries; // @synthesize entries=_entries;
- (id)_backgroundLabelTextColor;	// IMP=0x0000000000663cc5
- (_Bool)_shouldUseDarkAppearance;	// IMP=0x0000000000663c55
- (id)_indicatorShadowPath;	// IMP=0x0000000000663bbd
- (id)_backgroundFont;	// IMP=0x0000000000663b41
- (id)_foregroundFont;	// IMP=0x0000000000663ad9
- (void)_determinePreferredSizes;	// IMP=0x0000000000663618
- (void)_updateEmphasisBackgroundColor;	// IMP=0x0000000000663579
- (void)_updateColors;	// IMP=0x00000000006633d5
- (void)_createLabels;	// IMP=0x00000000006630be
- (void)_showReducedFocusProminence;	// IMP=0x0000000000662ee0
- (void)_showNormalFocusProminence;	// IMP=0x0000000000662d31
- (void)layoutSubviews;	// IMP=0x0000000000662835
- (void)destroyEmphasisBackgroundIfNecessary;	// IMP=0x00000000006627f3
- (void)toggleEmphasisBackgroundVisible:(_Bool)arg1;	// IMP=0x00000000006627c5
- (void)createEmphasisBackgroundIfNecessary;	// IMP=0x00000000006626df
- (void)resetDeflection:(_Bool)arg1;	// IMP=0x00000000006623f6
- (void)setIndexOfDeflectedEntry:(long long)arg1 amount:(double)arg2;	// IMP=0x0000000000661fba
- (id)_lowerEntryForOffset:(double)arg1;	// IMP=0x0000000000661dd9
- (id)_upperEntryForOffset:(double)arg1;	// IMP=0x0000000000661bff
- (double)_indicatorVerticalPositionForContentOffset:(struct CGPoint)arg1;	// IMP=0x00000000006616cd
- (void)updateForContentOffset:(struct CGPoint)arg1;	// IMP=0x00000000006615cd
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000000661375
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000000661308
- (_Bool)canBecomeFocused;	// IMP=0x0000000000661300
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;	// IMP=0x0000000000660f2e
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000000660f1a

@end

