//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusDebuggerStringOutput : NSObject
{
    NSString *_outputString;	// 8 = 0x8
}

+ (id)outputWithString:(id)arg1;	// IMP=0x00100000006034a8
- (void).cxx_destruct;	// IMP=0x0000000000603616
@property(readonly, copy) NSString *description;
- (id)initWithString:(id)arg1;	// IMP=0x000000000060350a
- (id)init;	// IMP=0x00000000006034f1

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

