//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_CarPlayTouchpad
{
}

+ (id)sharedInstance;	// IMP=0x0080000000175c65
- (_Bool)refinesIndexBarTargetContentOffset;	// IMP=0x0000000000175cfa
- (_Bool)shouldEnableFocusOnSelect;	// IMP=0x0000000000175cf2
- (_Bool)supportsIndirectPanningMovement;	// IMP=0x0000000000175cea

@end

