//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, UIScreen, _UIFocusDisplayLinkScrollAnimator;

__attribute__((visibility("hidden")))
@interface _UIFocusScrollManager : NSObject
{
    UIScreen *_screen;	// 8 = 0x8
    _UIFocusDisplayLinkScrollAnimator *_scrollAnimator;	// 16 = 0x10
    NSHashTable *_stackVisitedScrollingContainers;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000000066f8b4
@property(readonly, nonatomic) NSHashTable *stackVisitedScrollingContainers; // @synthesize stackVisitedScrollingContainers=_stackVisitedScrollingContainers;
@property(readonly, nonatomic) _UIFocusDisplayLinkScrollAnimator *scrollAnimator; // @synthesize scrollAnimator=_scrollAnimator;
@property(readonly, nonatomic) __weak UIScreen *screen; // @synthesize screen=_screen;
- (struct CGPoint)_contentOffsetForNonPagingContainer:(id)arg1 toShowFocusItemWithInfo:(id)arg2 itemFrame:(struct CGRect)arg3 heading:(unsigned long long)arg4 targetOffset:(struct CGPoint)arg5 targetBounds:(struct CGRect)arg6;	// IMP=0x000000000066ee9b
- (struct CGPoint)_differentialScrollingContentOffsetForContainer:(id)arg1 toShowFocusItemWithInfo:(id)arg2 itemFrame:(struct CGRect)arg3 heading:(unsigned long long)arg4 targetOffset:(struct CGPoint)arg5 targetBounds:(struct CGRect)arg6;	// IMP=0x000000000066e6eb
- (struct CGPoint)_contentOffsetForPagingContainer:(id)arg1 itemFrame:(struct CGRect)arg2 targetOffset:(struct CGPoint)arg3;	// IMP=0x000000000066e521
- (struct CGPoint)_contentOffsetForScrollableContainer:(id)arg1 toShowFocusItemWithInfo:(id)arg2 itemFrame:(struct CGRect)arg3 heading:(unsigned long long)arg4 targetOffset:(struct CGPoint)arg5 targetBounds:(struct CGRect)arg6;	// IMP=0x000000000066e3df
- (struct CGPoint)_contentOffsetForScrollableContainer:(id)arg1 toShowFocusItemWithInfo:(id)arg2 heading:(unsigned long long)arg3;	// IMP=0x000000000066df73
- (struct CGPoint)contentOffsetForScrollableContainer:(id)arg1 toShowRect:(struct CGRect)arg2 targetOffset:(struct CGPoint)arg3 targetBounds:(struct CGRect)arg4;	// IMP=0x000000000066df59
- (struct CGPoint)contentOffsetForScrollableContainer:(id)arg1 toShowFocusItem:(id)arg2 targetOffset:(struct CGPoint)arg3 targetBounds:(struct CGRect)arg4;	// IMP=0x000000000066de3c
- (struct CGPoint)_contentOffsetConsideredCurrentForScrollableContainer:(id)arg1;	// IMP=0x000000000066ddb0
- (void)_ensureFocusItemIsOnscreen:(id)arg1 inEnvironmentScrollableContainer:(id)arg2 heading:(unsigned long long)arg3;	// IMP=0x000000000066dacc
- (void)_scrollToFocusItemWithInfo:(id)arg1 offset:(struct CGPoint)arg2 inEnvironmentScrollableContainer:(id)arg3 heading:(unsigned long long)arg4;	// IMP=0x000000000066d230
- (void)adjustTargetContentOffsetForScrollableContainer:(id)arg1 byDelta:(struct CGPoint)arg2;	// IMP=0x000000000066d21a
- (void)animateOffsetOfScrollableContainersInParentEnvironmentContainer:(id)arg1 toShowFocusItem:(id)arg2;	// IMP=0x000000000066cf44
- (void)animateOffsetOfEnvironmentScrollableContainer:(id)arg1 toShowFocusItem:(id)arg2;	// IMP=0x000000000066cda7
- (struct CGPoint)currentVelocityForScrollableContainer:(id)arg1;	// IMP=0x000000000066cd91
- (struct CGPoint)targetContentOffsetForScrollableContainer:(id)arg1;	// IMP=0x000000000066cd7b
- (void)cancelScrollingForScrollableContainer:(id)arg1;	// IMP=0x000000000066cd65
- (_Bool)isScrollingScrollableContainer:(id)arg1;	// IMP=0x000000000066cd4f
- (void)performScrollingIfNeededForFocusUpdateInContext:(id)arg1;	// IMP=0x000000000066c555
- (id)initWithScreen:(id)arg1;	// IMP=0x000000000066c3d7

@end

