//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIPanGestureRecognizer.h"

@protocol _UIFocusEnginePanGestureRecognizerDelegate, _UIFocusEnginePanGestureTouchObserver;

__attribute__((visibility("hidden")))
@interface _UIFocusEnginePanGestureRecognizer : UIPanGestureRecognizer
{
    id <_UIFocusEnginePanGestureTouchObserver> _touchObserver;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000000060ef58
@property(nonatomic) __weak id <_UIFocusEnginePanGestureTouchObserver> touchObserver; // @synthesize touchObserver=_touchObserver;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000000060ee6c
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000000060edad
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000000060ecee
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000000060eb9f

// Remaining properties
@property(nonatomic) __weak id <_UIFocusEnginePanGestureRecognizerDelegate> delegate; // @dynamic delegate;

@end

