//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIPress;

__attribute__((visibility("hidden")))
@interface _UIFocusMovementTabulatorPressGestureRecognizer
{
    UIPress *_trackingPress;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000000009d8b91
@property(retain, nonatomic) UIPress *trackingPress; // @synthesize trackingPress=_trackingPress;
- (_Bool)_shouldReceivePress:(id)arg1;	// IMP=0x00000000009d8ad3
- (void)reset;	// IMP=0x00000000009d8a90
- (unsigned long long)focusHeadingForPresses:(id)arg1;	// IMP=0x00000000009d88f4
- (void)configureDefaults;	// IMP=0x00000000009d88ba

@end

