//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusFastScrollingEntryTrimmerDelegate : NSObject
{
}

- (id)_focusFastScrollingIndexBarEntryTrimmer:(id)arg1 placeholderEntryBetweenEntryBefore:(id)arg2 entryAfter:(id)arg3;	// IMP=0x000000000065f428
- (_Bool)_focusFastScrollingIndexBarEntryTrimmer:(id)arg1 entryIsPlaceholder:(id)arg2;	// IMP=0x000000000065f3a7
- (_Bool)_focusFastScrollingIndexBarEntryTrimmer:(id)arg1 startingOrEndingEntryMustBePreserved:(id)arg2;	// IMP=0x000000000065f2f7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

