//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PrototypeTools/PTDomain.h>

__attribute__((visibility("hidden")))
@interface _UIFocusSettingsDomain : PTDomain
{
}

+ (Class)rootSettingsClass;	// IMP=0x0080000000ef9246
+ (id)domainName;	// IMP=0x0080000000ef9239
+ (id)domainGroupName;	// IMP=0x0080000000ef922c
+ (id)rootSettings;	// IMP=0x0080000000ef91e5

@end

