//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_FKA : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00100000005c7703
- (_Bool)supportsLinearMovementDebugOverlay;	// IMP=0x00000000005c7a5f
- (_Bool)shouldCallAccessibilityOverrides;	// IMP=0x00000000005c7a57
- (_Bool)tabBasedMovementLoops;	// IMP=0x00000000005c7a4f
- (long long)skipKeyCommandsForKeyEvents;	// IMP=0x00000000005c7a47
- (long long)deliverKeyEventsToFocusEngine;	// IMP=0x00000000005c7a3f
- (_Bool)shouldSupressIndirectMovementOnSelect;	// IMP=0x00000000005c7a37
- (_Bool)shouldEnableFocusOnSelect;	// IMP=0x00000000005c7a2f
- (long long)pageButtonScrollingStyle;	// IMP=0x00000000005c7a27
- (_Bool)supportsArrowKeys;	// IMP=0x00000000005c7a1f
- (_Bool)supportsGameControllers;	// IMP=0x00000000005c79d4
- (_Bool)shouldConvertIndirectTapsIntoArrowKeys;	// IMP=0x00000000005c79cc
- (_Bool)supportsIndirectRotaryMovement;	// IMP=0x00000000005c79c4
- (_Bool)supportsIndirectPanningMovement;	// IMP=0x00000000005c79bc
- (_Bool)showsFocusRingForItem:(id)arg1;	// IMP=0x00000000005c79b4
- (_Bool)supportsParentFocusRings;	// IMP=0x00000000005c79ac
- (long long)focusRingVisibility;	// IMP=0x00000000005c79a1
- (long long)buttonSelectionMode;	// IMP=0x00000000005c7999
- (_Bool)refinesIndexBarTargetContentOffset;	// IMP=0x00000000005c7991
- (_Bool)isContainerEligibleForFocusUpdateSearchRoot:(id)arg1;	// IMP=0x00000000005c78dd
- (double)stabilizedLinearFocusMovementTimeout;	// IMP=0x00000000005c78d4
- (_Bool)wantsTreeLocking;	// IMP=0x00000000005c78cc
- (_Bool)throttlesProgrammaticFocusUpdates;	// IMP=0x00000000005c78c4
- (long long)focusCastingMode;	// IMP=0x00000000005c78bc
- (_Bool)supportsClipToBounds;	// IMP=0x00000000005c78a8
- (_Bool)supportViewTransparencyAndMultipleWindows;	// IMP=0x00000000005c7894
- (_Bool)treatFirstAndLastHeadingsAsGlobal;	// IMP=0x00000000005c788c
- (_Bool)defaultValueForSelectionFollowsFocusInTableView:(id)arg1;	// IMP=0x00000000005c7884
- (_Bool)defaultValueForSelectionFollowsFocusInCollectionView:(id)arg1;	// IMP=0x00000000005c787c
- (_Bool)preventsCellFocusabilityWhileEditing;	// IMP=0x00000000005c7874
- (long long)cellFocusability;	// IMP=0x00000000005c786c
- (_Bool)shouldUseAccessibilityCompareForItemGeometry;	// IMP=0x00000000005c7864
- (long long)scrollingMode;	// IMP=0x00000000005c7859
- (_Bool)useDifferentialScrollTrigger;	// IMP=0x00000000005c7851
- (_Bool)enforcesStrictTargetContentOffsetAdjustmentBehavior;	// IMP=0x00000000005c7849
- (unsigned long long)focusGroupContainmentBehavior;	// IMP=0x00000000005c783e
- (unsigned long long)focusGroupMovementBehavior;	// IMP=0x00000000005c7833
- (long long)indirectMovementPriority;	// IMP=0x00000000005c782b
- (_Bool)supportsTabKey;	// IMP=0x00000000005c7823
- (_Bool)includesContentScrollViewInPreferredFocusEnvironments;	// IMP=0x00000000005c781b
- (_Bool)searchBarTextFieldCanBecomeFocused;	// IMP=0x00000000005c7813
- (_Bool)tabBarButtonCanBecomeFocused;	// IMP=0x00000000005c780b
- (_Bool)tabBarCanBecomeFocused;	// IMP=0x00000000005c7803
- (_Bool)textViewCanBecomeFocused:(id)arg1;	// IMP=0x00000000005c77ee
- (_Bool)controlCanBecomeFocused:(id)arg1;	// IMP=0x00000000005c77e6
- (_Bool)ignoresKeyWindowStatusWhenRestoringFocus;	// IMP=0x00000000005c77de
- (long long)focusDeferral;	// IMP=0x00000000005c77d6
- (_Bool)syncsFocusAndResponder;	// IMP=0x00000000005c77ce
- (long long)requiredInputDevices;	// IMP=0x00000000005c7798
- (_Bool)honorsFocusSystemEnabledInfoPlistKey;	// IMP=0x00000000005c7790
- (_Bool)wantsFocusSystemForScene:(id)arg1;	// IMP=0x00000000005c7788

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

