//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_TV : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00100000010a044b
- (_Bool)supportsLinearMovementDebugOverlay;	// IMP=0x00000000010a0971
- (_Bool)shouldCallAccessibilityOverrides;	// IMP=0x00000000010a0969
- (void)_handleRemoteTouchSurfaceTypeDidChangeNotification:(id)arg1;	// IMP=0x00000000010a0919
- (_Bool)tabBasedMovementLoops;	// IMP=0x00000000010a0911
- (long long)skipKeyCommandsForKeyEvents;	// IMP=0x00000000010a0909
- (long long)deliverKeyEventsToFocusEngine;	// IMP=0x00000000010a08fe
- (_Bool)shouldSupressIndirectMovementOnSelect;	// IMP=0x00000000010a08f4
- (_Bool)shouldEnableFocusOnSelect;	// IMP=0x00000000010a08ec
- (long long)indirectMovementPriority;	// IMP=0x00000000010a08ae
- (_Bool)supportsTabKey;	// IMP=0x00000000010a08a6
- (long long)pageButtonScrollingStyle;	// IMP=0x00000000010a0851
- (_Bool)supportsArrowKeys;	// IMP=0x00000000010a0849
- (_Bool)supportsGameControllers;	// IMP=0x00000000010a0841
- (_Bool)shouldConvertIndirectTapsIntoArrowKeys;	// IMP=0x00000000010a081d
- (_Bool)supportsIndirectRotaryMovement;	// IMP=0x00000000010a0739
- (_Bool)supportsIndirectPanningMovement;	// IMP=0x00000000010a0731
- (_Bool)showsFocusRingForItem:(id)arg1;	// IMP=0x00000000010a0729
- (_Bool)supportsParentFocusRings;	// IMP=0x00000000010a0721
- (long long)focusRingVisibility;	// IMP=0x00000000010a0719
- (long long)buttonSelectionMode;	// IMP=0x00000000010a070e
- (_Bool)refinesIndexBarTargetContentOffset;	// IMP=0x00000000010a0706
- (_Bool)isContainerEligibleForFocusUpdateSearchRoot:(id)arg1;	// IMP=0x00000000010a06f1
- (double)stabilizedLinearFocusMovementTimeout;	// IMP=0x00000000010a06e8
- (_Bool)wantsTreeLocking;	// IMP=0x00000000010a06e0
- (_Bool)throttlesProgrammaticFocusUpdates;	// IMP=0x00000000010a06d8
- (long long)focusCastingMode;	// IMP=0x00000000010a06cd
- (_Bool)supportsClipToBounds;	// IMP=0x00000000010a06b9
- (_Bool)supportViewTransparencyAndMultipleWindows;	// IMP=0x00000000010a06b1
- (_Bool)treatFirstAndLastHeadingsAsGlobal;	// IMP=0x00000000010a06a9
- (_Bool)defaultValueForSelectionFollowsFocusInTableView:(id)arg1;	// IMP=0x00000000010a06a1
- (_Bool)defaultValueForSelectionFollowsFocusInCollectionView:(id)arg1;	// IMP=0x00000000010a0699
- (_Bool)preventsCellFocusabilityWhileEditing;	// IMP=0x00000000010a0691
- (long long)cellFocusability;	// IMP=0x00000000010a0689
- (_Bool)shouldUseAccessibilityCompareForItemGeometry;	// IMP=0x00000000010a0681
- (long long)scrollingMode;	// IMP=0x00000000010a0679
- (_Bool)useDifferentialScrollTrigger;	// IMP=0x00000000010a0671
- (_Bool)enforcesStrictTargetContentOffsetAdjustmentBehavior;	// IMP=0x00000000010a0669
- (unsigned long long)focusGroupContainmentBehavior;	// IMP=0x00000000010a065e
- (unsigned long long)focusGroupMovementBehavior;	// IMP=0x00000000010a0653
- (_Bool)includesContentScrollViewInPreferredFocusEnvironments;	// IMP=0x00000000010a064b
- (_Bool)searchBarTextFieldCanBecomeFocused;	// IMP=0x00000000010a0643
- (_Bool)tabBarButtonCanBecomeFocused;	// IMP=0x00000000010a063b
- (_Bool)tabBarCanBecomeFocused;	// IMP=0x00000000010a0633
- (_Bool)textViewCanBecomeFocused:(id)arg1;	// IMP=0x00000000010a061e
- (_Bool)controlCanBecomeFocused:(id)arg1;	// IMP=0x00000000010a0616
- (_Bool)ignoresKeyWindowStatusWhenRestoringFocus;	// IMP=0x00000000010a060e
- (long long)focusDeferral;	// IMP=0x00000000010a0606
- (_Bool)syncsFocusAndResponder;	// IMP=0x00000000010a05fe
- (long long)requiredInputDevices;	// IMP=0x00000000010a05f6
- (_Bool)honorsFocusSystemEnabledInfoPlistKey;	// IMP=0x00000000010a05ee
- (_Bool)wantsFocusSystemForScene:(id)arg1;	// IMP=0x00000000010a05e6
- (void)dealloc;	// IMP=0x00000000010a0564
- (id)init;	// IMP=0x00000000010a04d0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

