//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIWindow.h"

@class NSArray, NSTimer, UIScrollView;

__attribute__((visibility("hidden")))
@interface _UIFocusDebugWindow : UIWindow
{
    NSTimer *_timer;	// 304 = 0x130
    NSArray *_cacheModules;	// 312 = 0x138
    UIScrollView *_scrollView;	// 320 = 0x140
    struct CGPoint _lastDragPoint;	// 328 = 0x148
}

+ (_Bool)_isSystemWindow;	// IMP=0x0060000000c1442e
+ (_Bool)hasAnyModules;	// IMP=0x0060000000c143e6
+ (id)moduleClasses;	// IMP=0x0060000000887140
- (void).cxx_destruct;	// IMP=0x0000000000c1526e
- (void)_update:(id)arg1;	// IMP=0x0000000000c1510f
- (void)_updateTimer;	// IMP=0x0000000000c1502c
- (void)_searchForFocusRegionsInContext:(id)arg1;	// IMP=0x0000000000c15026
- (_Bool)_isEligibleForFocusOcclusion;	// IMP=0x0000000000c1501e
- (_Bool)isTransparentFocusItem;	// IMP=0x0000000000c15016
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000000c14f23
- (void)setHidden:(_Bool)arg1;	// IMP=0x0000000000c14ee2
- (void)drag:(id)arg1;	// IMP=0x0000000000c14dd2
- (id)initWithWindowScene:(id)arg1;	// IMP=0x0000000000c1443e
- (_Bool)canBecomeKeyWindow;	// IMP=0x0000000000c14436

@end

