//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol _UIFocusMovementPerformerDelegate;

__attribute__((visibility("hidden")))
@interface _UIFocusMovementPerformer : NSObject
{
    id <_UIFocusMovementPerformerDelegate> _delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000000064b287
@property(nonatomic) __weak id <_UIFocusMovementPerformerDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)_minimumSearchAreaForContainer:(id)arg1 inWindow:(id)arg2 shouldLoadScrollableContainer:(_Bool)arg3;	// IMP=0x000000000064af7b
- (struct CGRect)_minimumSearchAreaForContainer:(id)arg1 inWindow:(id)arg2;	// IMP=0x000000000064af56
- (_Bool)_isMovementValidForFocusSequences:(id)arg1;	// IMP=0x000000000064ac1a
- (id)_nextLinearCandidateLoadingScrollableContentForRequest:(id)arg1;	// IMP=0x0000000000649e4f
- (id)_fakeFocusedViewForFocusMovement:(id)arg1 searchArea:(struct CGRect)arg2 window:(id)arg3;	// IMP=0x0000000000649ce1
- (id)_environmentContainersToCheckForRequest:(id)arg1;	// IMP=0x000000000064953f
- (id)_bestCandidateForFocusMovement:(id)arg1;	// IMP=0x0000000000649495
- (id)_bestCandidateForLinearFocusMovement:(id)arg1;	// IMP=0x0000000000649275
- (id)_bestCandidateForNonLinearFocusMovement:(id)arg1;	// IMP=0x0000000000648aa2
- (id)_findFocusCandidateBySearchingLinearFocusMovementSequencesForRequest:(id)arg1;	// IMP=0x0000000000648498
- (id)_findFocusCandidateByExhaustivelySearchingEnvironment:(id)arg1 scrollableContainer:(id)arg2 forRequest:(id)arg3;	// IMP=0x0000000000647aeb
- (_Bool)_shouldRecordDestinationItemDistanceOffscreenInWindow:(id)arg1;	// IMP=0x0000000000647a9f
- (id)_findFocusCandidateWithoutLoadingScrollableContentInEnvironment:(id)arg1 container:(id)arg2 forRequest:(id)arg3 minimumSearchArea:(struct CGRect)arg4;	// IMP=0x0000000000647a8a
- (id)__findFocusCandidateInEnvironment:(id)arg1 container:(id)arg2 forRequest:(id)arg3 minimumSearchArea:(struct CGRect)arg4 isLoadingScrollableContainer:(_Bool)arg5;	// IMP=0x0000000000647824
- (id)viewForFocusHeading:(unsigned long long)arg1 fromView:(id)arg2;	// IMP=0x00000000006475f7
- (_Bool)performFocusMovement:(id)arg1;	// IMP=0x000000000064703d

@end

