//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusHardwareKeyboardObserver
{
}

- (_Bool)isActive;	// IMP=0x000000000125cddb
- (void)dealloc;	// IMP=0x000000000125cd59
- (id)init;	// IMP=0x000000000125ccc5
- (void)_hardwareKeyboardAvailabilityChanged:(id)arg1;	// IMP=0x000000000125ccb3

@end

