//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface _UIFocusDebugWindowLabelModule : UIView
{
    UILabel *_content;	// 144 = 0x90
}

- (void).cxx_destruct;	// IMP=0x0000000000c15b24
- (void)update;	// IMP=0x0000000000c15ad0
- (id)updatedAttributedLabelContent;	// IMP=0x0000000000c15a67
- (id)updatedLabelContent;	// IMP=0x0000000000c159da
- (id)title;	// IMP=0x0000000000c159cd
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000000c15607

@end

