//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMapTable, NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusActiveSceneObserver_Classic
{
    NSMapTable *_hidObserverMapTable;	// 16 = 0x10
    struct {
        unsigned int supportsHIDUpdates:1;
    } _flags;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000000001574d3
- (id)descriptionBuilder;	// IMP=0x0000000000157416
- (void)_keyWindowDidChangeNotification:(id)arg1;	// IMP=0x00000000001573a1
- (void)observerDeliveryPolicyDidChange:(id)arg1;	// IMP=0x000000000015732c
- (void)_windowDidDetachContext:(id)arg1;	// IMP=0x00000000001572ae
- (void)_windowDidAttachContext:(id)arg1;	// IMP=0x0000000000157230
- (void)_removeDeliverObserverForWindow:(id)arg1;	// IMP=0x0000000000157195
- (void)_addDeliveryObserverForWindow:(id)arg1;	// IMP=0x0000000000156f8d
- (_Bool)isActive;	// IMP=0x0000000000156d11
- (void)dealloc;	// IMP=0x0000000000156b78
- (void)stopMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x0000000000156a83
- (void)beginMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x0000000000156980
- (id)_initWithScene:(id)arg1;	// IMP=0x00000000001568aa

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

