//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CADisplayLink, NSArray, NSSet, NSString, NSTimer, UIMoveEvent, UIScrollView, UITapGestureRecognizer, UIView, _UIFocusEffectsController, _UIFocusEnableOnSelectGestureRecognizer, _UIFocusEngineJoystickGestureRecognizer, _UIFocusEnginePanGestureRecognizer, _UIFocusFastScrollingRecognizer, _UIFocusLinearMovementDebugGestureRecognizer, _UIFocusLinearMovementDebugView, _UIFocusMovementDirectionalPressGestureRecognizer, _UIFocusMovementInfo, _UIFocusMovementTabulatorPressGestureRecognizer, _UIFocusSelectObserverGestureRecognizer, _UIRotaryGestureRecognizer;
@protocol _UIFocusEventRecognizerDelegate;

__attribute__((visibility("hidden")))
@interface _UIFocusEventRecognizer : NSObject
{
    _UIFocusEnginePanGestureRecognizer *_panGestureRecognizer;	// 8 = 0x8
    UITapGestureRecognizer *_tapGestureRecognizer;	// 16 = 0x10
    _UIFocusEnableOnSelectGestureRecognizer *_selectGestureRecognizer;	// 24 = 0x18
    _UIFocusSelectObserverGestureRecognizer *_selectObserverGestureRecognizer;	// 32 = 0x20
    _UIRotaryGestureRecognizer *_rotaryGestureRecognizer;	// 40 = 0x28
    double _panDeadBand;	// 48 = 0x30
    _UIFocusLinearMovementDebugGestureRecognizer *_linearDebugGestureRecognizer;	// 56 = 0x38
    _UIFocusLinearMovementDebugView *_linearDebugView;	// 64 = 0x40
    struct CGPoint _touchBeganPoint;	// 72 = 0x48
    struct CGPoint _lastKnownTouchPoint;	// 88 = 0x58
    struct CGPoint _previousPoints[5];	// 104 = 0x68
    int _numFrames;	// 184 = 0xb8
    struct CGVector _progressAccumulator;	// 192 = 0xc0
    struct CGVector _unlockedAccumulator;	// 208 = 0xd0
    double _lastButtonPressTime;	// 224 = 0xe0
    unsigned long long _failedContinuousMovementHeading;	// 232 = 0xe8
    _UIFocusFastScrollingRecognizer *_fastScrollingRecognizer;	// 240 = 0xf0
    struct CGPoint _firstMomentumTouchPoint;	// 248 = 0xf8
    struct CGPoint _lastMomentumTouchPoint;	// 264 = 0x108
    struct CGPoint _momentumVelocity;	// 280 = 0x118
    double _momentumFriction;	// 296 = 0x128
    unsigned long long _focusUpdateCountSinceLastContinuousMovementBegan;	// 304 = 0x130
    CADisplayLink *_momentumDisplayLink;	// 312 = 0x138
    _UIFocusMovementDirectionalPressGestureRecognizer *_arrowButtonGesture;	// 320 = 0x140
    _UIFocusMovementDirectionalPressGestureRecognizer *_pageButtonGesture;	// 328 = 0x148
    _UIFocusMovementTabulatorPressGestureRecognizer *_tabulatorGesture;	// 336 = 0x150
    NSSet *_gesturesForFailureRequirements;	// 344 = 0x158
    _UIFocusEngineJoystickGestureRecognizer *_joystickGestureRecognizer;	// 352 = 0x160
    NSTimer *_joystickModeExitTimer;	// 360 = 0x168
    NSTimer *_joystickModeRepeatTimer;	// 368 = 0x170
    double _previousJoystickFocusMovementTime;	// 376 = 0x178
    double _previousJoystickRegionEntryTime;	// 384 = 0x180
    unsigned long long _joystickRepeatingHeading;	// 392 = 0x188
    CADisplayLink *_joystickFocusDirectionDisplayLink;	// 400 = 0x190
    _UIFocusMovementInfo *_previousJoystickFocusMovementInfo;	// 408 = 0x198
    long long _joystickRepeatCount;	// 416 = 0x1a0
    UIScrollView *_lastScrolledScroll;	// 424 = 0x1a8
    double _lastEdgeScrollEdgeValue;	// 432 = 0x1b0
    unsigned long long _inputType;	// 440 = 0x1b8
    struct {
        unsigned int isEligibleToCrossSpeedBump:1;
        unsigned int isContinuingTouchWithMomentum:1;
        unsigned int isPerformingJoystickRollback:1;
        unsigned int isJoystickInRepeatMode:1;
        unsigned int isPendingJoystickRepeat:1;
        unsigned int isFastScrolling:1;
        unsigned int shouldApplyAcceleration:1;
        unsigned int shouldSupressActiveIndirectMotionUpdates:1;
    } _flags;	// 448 = 0x1c0
    _Bool _enabled;	// 452 = 0x1c4
    _Bool _supportsFastScrolling;	// 453 = 0x1c5
    UIView *_owningView;	// 456 = 0x1c8
    NSArray *_keyCommands;	// 464 = 0x1d0
    id <_UIFocusEventRecognizerDelegate> _delegate;	// 472 = 0x1d8
    UIMoveEvent *_moveEvent;	// 480 = 0x1e0
    _UIFocusEffectsController *_motionEffectsController;	// 488 = 0x1e8
}

+ (_Bool)_canSupportFastScrolling;	// IMP=0x0010000000617d68
- (void).cxx_destruct;	// IMP=0x00000000006183f5
@property(readonly, nonatomic, getter=_motionEffectsController) _UIFocusEffectsController *motionEffectsController; // @synthesize motionEffectsController=_motionEffectsController;
@property(retain, nonatomic, getter=_moveEvent, setter=_setMoveEvent:) UIMoveEvent *moveEvent; // @synthesize moveEvent=_moveEvent;
@property(nonatomic) __weak id <_UIFocusEventRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool supportsFastScrolling; // @synthesize supportsFastScrolling=_supportsFastScrolling;
@property(readonly, nonatomic) NSArray *keyCommands; // @synthesize keyCommands=_keyCommands;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) __weak UIView *owningView; // @synthesize owningView=_owningView;
- (void)_uiktest_handlePanGesture:(id)arg1;	// IMP=0x000000000061833e
- (id)_uiktest_panGestureRecognizer;	// IMP=0x0000000000618330
- (void)_uiktest_setPanGestureRecognizer:(id)arg1;	// IMP=0x000000000061831f
- (void)_sendGestureBeginNotification;	// IMP=0x00000000006182bf
- (_Bool)_isRotaryFastScrolling;	// IMP=0x0000000000618270
- (void)_fastScrollingEnded;	// IMP=0x0000000000618240
- (void)_fastScrollingBeganInScrollView:(id)arg1;	// IMP=0x00000000006181af
- (void)fastScrollingRecognizer:(id)arg1 didRecognizeFastScrollingRequest:(id)arg2;	// IMP=0x0000000000617e69
- (void)_createFastScrollingRecognizerIfNeeded;	// IMP=0x0000000000617dd5
- (void)_setSupportsFastScrolling:(_Bool)arg1;	// IMP=0x0000000000617d93
- (void)_sendMomentumEndNotificationsAndAnimateRollback:(_Bool)arg1;	// IMP=0x0000000000617d25
- (void)_stopMomentumAndPerformRollback;	// IMP=0x0000000000617cd3
- (_Bool)_shouldPerformFocusUpdateWithCurrentMomentumStatus;	// IMP=0x0000000000617c5a
- (void)_momentumHeartbeat:(id)arg1;	// IMP=0x000000000061796d
- (id)_momentumMovementRequestWithHeading:(unsigned long long)arg1;	// IMP=0x0000000000617869
- (unsigned long long)_momentumFocusHeadingForAccumulator:(struct CGVector)arg1;	// IMP=0x0000000000617810
- (void)_beginMomentumImmediatelyWithVelocity:(struct CGPoint)arg1 friction:(double)arg2;	// IMP=0x00000000006176eb
- (void)_continueTouchWithMomentum;	// IMP=0x000000000061752e
- (void)_recordMomentumForPoint:(struct CGPoint)arg1 reportedVelocity:(struct CGPoint)arg2;	// IMP=0x00000000006174ac
- (void)_resetMomentum;	// IMP=0x0000000000617446
- (struct CGSize)_momentumReferenceSize;	// IMP=0x00000000006172a9
- (void)_resetMotionEffects;	// IMP=0x0000000000617290
- (void)_resetJoystick;	// IMP=0x00000000006171e9
- (void)_joystickDisplayLinkHeartbeat:(id)arg1;	// IMP=0x0000000000616f95
- (unsigned long long)_headingForJoystickPosition:(struct CGPoint)arg1 usingMinimumRadius:(double)arg2;	// IMP=0x0000000000616f05
- (struct CGVector)_joystickVelocityForHeading:(unsigned long long)arg1;	// IMP=0x0000000000616ed5
- (id)_focusMovementForJoystickPosition:(struct CGPoint)arg1 usingMinimumRadius:(double)arg2 focusMovementStyle:(long long)arg3;	// IMP=0x0000000000616d8d
- (_Bool)_joystickFocusMovement:(id)arg1 shouldBeConsideredEqualToFocusMovement:(id)arg2;	// IMP=0x0000000000616c7b
- (double)_joystickRepeatDurationForTimeInMovementZone:(double)arg1;	// IMP=0x0000000000616aae
- (void)_joystickPerformRepeat:(id)arg1;	// IMP=0x0000000000616aa1
- (_Bool)_joystickAttemptFocusMovementWithRequest:(id)arg1;	// IMP=0x00000000006169fc
- (void)_handleJoystickTiltMode:(id)arg1;	// IMP=0x00000000006166da
- (void)_handleJoystickRepeatMode:(id)arg1;	// IMP=0x0000000000616357
- (void)_exitJoystickModeForReal:(id)arg1;	// IMP=0x0000000000616313
- (void)_joystickGestureEnded:(id)arg1;	// IMP=0x00000000006161d5
- (void)_joystickGestureUpdated:(id)arg1;	// IMP=0x00000000006161ae
- (void)_joystickGestureBegan:(id)arg1;	// IMP=0x0000000000616051
- (void)_resetFailedMovementHeading;	// IMP=0x0000000000616040
- (void)_resetContinuousMovementState;	// IMP=0x0000000000616028
- (void)_resetProgressAccumulatorWithHeading:(unsigned long long)arg1;	// IMP=0x0000000000615f17
- (void)_panGestureCancelled:(id)arg1;	// IMP=0x0000000000615ee5
- (void)_panGestureEnd:(id)arg1;	// IMP=0x0000000000615eb0
- (void)_cleanupPanMomentumWithAccumulator:(struct CGVector)arg1 movementSuccess:(_Bool)arg2;	// IMP=0x0000000000615e6e
- (void)_continuousMovementFailedWithPrimaryHeading:(unsigned long long)arg1;	// IMP=0x0000000000615de7
- (void)_continuousMovementSucceededWithDirectionalHeading:(unsigned long long)arg1;	// IMP=0x0000000000615d1e
- (_Bool)_attemptToRecognizeContinuousMovementRequest:(id)arg1;	// IMP=0x0000000000615c8a
- (id)_createMovementInfoForHeading:(unsigned long long)arg1 groupFilter:(long long)arg2 acceleratedVelocity:(struct CGPoint)arg3;	// IMP=0x0000000000615c0e
- (_Bool)_attemptPanFocusMovementWithHeading:(unsigned long long)arg1 request:(id)arg2 acceleratedVelocity:(struct CGPoint)arg3 studyLogData:(id)arg4;	// IMP=0x0000000000615b05
- (unsigned long long)_calculateDirectionalHeadingForAccumulator:(struct CGVector)arg1 studyLogData:(id)arg2;	// IMP=0x0000000000615a90
- (void)_updateMotionEffectsControllerWithProgressAccumulator:(struct CGVector)arg1 unlockedAccumulator:(struct CGVector)arg2;	// IMP=0x0000000000615a55
- (void)_updateAccumulatorsWithScaledDelta:(struct CGPoint)arg1 unlockedDelta:(struct CGPoint)arg2 studyLogData:(id)arg3;	// IMP=0x0000000000615a1f
- (struct CGVector)_accelerationFactorForCurrentVelocity:(struct CGPoint)arg1 isRotaryGesture:(_Bool)arg2 isFocusInKeyboard:(_Bool)arg3 remoteTouchSurfaceType:(unsigned long long)arg4;	// IMP=0x0000000000615798
- (struct CGPoint)_applyButtonMaskTimeToValue:(struct CGPoint)arg1 remoteTouchSurfaceType:(unsigned long long)arg2;	// IMP=0x0000000000615758
- (struct CGPoint)_applyAxisLockingForNormalizedPoint:(struct CGPoint)arg1 toDelta:(struct CGPoint)arg2;	// IMP=0x000000000061563b
- (struct CGPoint)_applyHorizontalFlipForFocusItemInfo:(id)arg1 toDelta:(struct CGPoint)arg2;	// IMP=0x00000000006155fa
- (struct CGPoint)_applyPanDeadbandToValue:(struct CGPoint)arg1 startPoint:(struct CGPoint)arg2 currentPoint:(struct CGPoint)arg3 remoteTouchSurfaceType:(unsigned long long)arg4;	// IMP=0x00000000006154b5
- (struct CGPoint)_calculateDeltaForNormalizedPoint:(struct CGPoint)arg1 studyLogData:(id)arg2;	// IMP=0x000000000061548c
- (id)_createStudyLogDataForPanNormalizedPoint:(struct CGPoint)arg1 reportedVelocity:(struct CGPoint)arg2;	// IMP=0x0000000000615484
- (id)_createPanMovementRequestWithFocusSystem:(id)arg1;	// IMP=0x00000000006153df
- (void)_updatePanLocation:(struct CGPoint)arg1 reportedVelocity:(struct CGPoint)arg2 remoteTouchSurfaceType:(unsigned long long)arg3;	// IMP=0x0000000000614d6b
- (void)_panGestureStart:(id)arg1;	// IMP=0x0000000000614c66
- (_Bool)focusEnginePanGestureRecognizerShouldRecognizeImmediately:(id)arg1;	// IMP=0x0000000000614c56
- (void)_resetPanDeadband;	// IMP=0x0000000000614c11
- (_Bool)_attemptRotaryFocusMovementWithLinearHeading:(unsigned long long)arg1 directionalHeading:(unsigned long long)arg2 request:(id)arg3 acceleratedVelocity:(struct CGPoint)arg4 studyLogData:(id)arg5;	// IMP=0x0000000000614adc
- (unsigned long long)_calculateLinearHeadingForAccumulator:(struct CGVector)arg1 studyLogData:(id)arg2;	// IMP=0x0000000000614a8f
- (struct CGPoint)_pointForLinearValue:(double)arg1;	// IMP=0x0000000000614a44
- (id)_createRotaryMovementRequestWithFocusSystem:(id)arg1;	// IMP=0x000000000061499f
- (id)_createStudyLogDataForRotaryDistance:(double)arg1 delta:(double)arg2 reportedVelocity:(double)arg3;	// IMP=0x0000000000614997
- (void)_updateRotaryDistance:(double)arg1 delta:(double)arg2 reportedVelocity:(double)arg3 remoteTouchSurfaceType:(unsigned long long)arg4;	// IMP=0x0000000000614413
- (void)_handleRotaryCancelled:(id)arg1;	// IMP=0x00000000006143e1
- (void)_handleRotaryEnd:(id)arg1;	// IMP=0x0000000000614397
- (void)_handleRotaryBegin:(id)arg1;	// IMP=0x000000000061432b
- (void)_handleRotaryGesture:(id)arg1;	// IMP=0x00000000006140de
- (void)_resetProgressAccumulator;	// IMP=0x00000000006140c7
- (id)_globalCoordinateSpace;	// IMP=0x0000000000614077
- (id)_focusSystemSceneComponent;	// IMP=0x0000000000613fd6
- (_Bool)_canFastScrollWithRotaryInputInCurrentFocusContext;	// IMP=0x0000000000613f73
- (_Bool)_canMoveFocusWithRotaryInputInFocusContext:(id)arg1;	// IMP=0x0000000000613ede
- (_Bool)_shouldAcceptInputType:(unsigned long long)arg1;	// IMP=0x0000000000613d1f
- (struct CGSize)_touchSensitivityForItem:(id)arg1 remoteTouchSurfaceType:(unsigned long long)arg2;	// IMP=0x00000000006136f4
- (int)_touchRegionForDigitizerLocation:(struct CGPoint)arg1;	// IMP=0x00000000006135a4
- (_Bool)_buttonMaskTimeHasExpired;	// IMP=0x000000000061354c
- (id)currentFocusBehavior;	// IMP=0x0000000000613506
- (void)rotaryGestureRecognizerFailedToBeginFromRest:(id)arg1;	// IMP=0x00000000006134ed
- (void)rotaryGestureRecognizerIsAttemptingToBeginFromRest:(id)arg1;	// IMP=0x00000000006134cf
- (_Bool)rotaryGestureRecognizerMustBeginFromRest:(id)arg1;	// IMP=0x0000000000613467
- (_Bool)rotaryGestureRecognizerCanBeginFromRest:(id)arg1;	// IMP=0x000000000061340d
- (void)_gestureRecognizerFailed:(id)arg1;	// IMP=0x00000000006133c7
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x00000000006133b7
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x000000000061323c
- (_Bool)_hideLinearDebugOverlayIfNecessary:(_Bool)arg1;	// IMP=0x00000000006130da
- (void)_showLinearDebugOverlay:(_Bool)arg1;	// IMP=0x0000000000612c48
- (void)_handleLinearDebugOverlayGesture:(id)arg1;	// IMP=0x0000000000612b8c
- (void)_handleJoystickGesture:(id)arg1;	// IMP=0x0000000000612adf
- (void)_handleTapGesture:(id)arg1;	// IMP=0x00000000006129d6
- (void)_handlePanGesture:(id)arg1;	// IMP=0x00000000006127cd
- (void)_handleTabulatorGesture:(id)arg1;	// IMP=0x000000000061254f
- (void)_handlePageButtonGesture:(id)arg1;	// IMP=0x000000000061231f
- (void)_handleArrowButtonGesture:(id)arg1;	// IMP=0x0000000000612035
- (void)_handleSelectObserverGesture:(id)arg1;	// IMP=0x0000000000611fc0
- (void)_handleSelectGesture:(id)arg1;	// IMP=0x0000000000611f83
- (_Bool)_moveInDirection:(unsigned long long)arg1 groupFilter:(long long)arg2 withEvaluator:(CDUnknownBlockType)arg3;	// IMP=0x0000000000611efa
- (_Bool)_moveInDirection:(unsigned long long)arg1 groupFilter:(long long)arg2 withSearchInfo:(id)arg3;	// IMP=0x0000000000611d9d
- (_Bool)_moveInDirection:(unsigned long long)arg1 groupFilter:(long long)arg2;	// IMP=0x0000000000611d88
- (_Bool)_moveWithEvent:(id)arg1;	// IMP=0x0000000000611c75
- (_Bool)_didRecognizeFocusMovementRequest:(id)arg1;	// IMP=0x0000000000611b7c
- (id)_focusMovementSystem;	// IMP=0x0000000000611a8a
- (void)_focusSystemEnabledStateDidChange:(id)arg1;	// IMP=0x000000000061199e
- (void)_focusBehaviorDidChange:(id)arg1;	// IMP=0x000000000061198a
@property(readonly, nonatomic) NSSet *gesturesForFailureRequirements;
- (void)_updateGestureRecognizersForcingRemoval:(_Bool)arg1;	// IMP=0x000000000061175f
- (void)_pageButtonGestureUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x0000000000611443
- (void)_rotaryGestureRecognizerUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x00000000006110e8
- (void)_arrowButtonGestureUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x0000000000610dd9
- (void)_tabulatorGestureUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x0000000000610aca
- (void)_joystickGestureRecognizerUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x0000000000610789
- (void)_tapGestureRecognizerUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x00000000006103fc
- (void)_selectObserverGestureRecognizerUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x00000000006100f9
- (void)_selectGestureRecognizerUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x000000000060fdf6
- (void)_panGestureRecognizerUpdateForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x000000000060fa9f
- (void)reset;	// IMP=0x000000000060fa1c
- (void)dealloc;	// IMP=0x000000000060f8fd
- (id)initWithOwningView:(id)arg1;	// IMP=0x000000000060f567
- (id)init;	// IMP=0x000000000060f4e0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

