//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusMovementDirectionalPressGestureRecognizer
{
    struct {
        unsigned int determinedPressSource:1;
    } _flags;	// 8 = 0x8
    unsigned long long _pressSource;	// 16 = 0x10
}

@property(nonatomic) unsigned long long pressSource; // @synthesize pressSource=_pressSource;
- (void)reset;	// IMP=0x0000000000e52f58
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000e52ed4
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000e52e50
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000e52dcc
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000e52bb2
- (id)_filterPressesByPressSource:(id)arg1;	// IMP=0x0000000000e529cc
- (unsigned long long)focusHeadingForPresses:(id)arg1;	// IMP=0x0000000000e5282e
- (void)configureDefaults;	// IMP=0x0000000000e527f4

@end

