//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol UIFocusEnvironment, UIFocusItemScrollableContainer;

__attribute__((visibility("hidden")))
@interface _UIFocusEnvironmentScrollableContainerTuple : NSObject
{
    id <UIFocusEnvironment> _owningEnvironment;	// 8 = 0x8
    id <UIFocusItemScrollableContainer> _scrollableContainer;	// 16 = 0x10
}

+ (id)tupleWithScrollView:(id)arg1;	// IMP=0x00600000005fba07
+ (id)tupleWithOwningEnvironment:(id)arg1 scrollableContainer:(id)arg2;	// IMP=0x00600000005fb99b
- (void).cxx_destruct;	// IMP=0x00000000005fbff8
@property(readonly, nonatomic) id <UIFocusItemScrollableContainer> scrollableContainer; // @synthesize scrollableContainer=_scrollableContainer;
@property(readonly, nonatomic) id <UIFocusEnvironment> owningEnvironment; // @synthesize owningEnvironment=_owningEnvironment;
- (id)description;	// IMP=0x00000000005fbf67
- (unsigned long long)hash;	// IMP=0x00000000005fbeda
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000000005fba53
- (id)initWithOwningEnvironment:(id)arg1 scrollableContainer:(id)arg2;	// IMP=0x00000000005fb775

@end

