//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, _UIDynamicValueConvergenceAnimation;

__attribute__((visibility("hidden")))
@interface _UIFocusEffectsController : NSObject
{
    _UIDynamicValueConvergenceAnimation *_rollbackAnimation;	// 8 = 0x8
    NSHashTable *_observers;	// 16 = 0x10
    struct CGPoint _displayOffset;	// 24 = 0x18
    double _displayMovementAdjustment;	// 40 = 0x28
    _Bool _displayOffsetAccumulatorEnabled;	// 48 = 0x30
    struct CGPoint _currentOffset;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000000061aa72
@property(nonatomic) _Bool displayOffsetAccumulatorEnabled; // @synthesize displayOffsetAccumulatorEnabled=_displayOffsetAccumulatorEnabled;
@property(readonly, nonatomic) struct CGPoint currentOffset; // @synthesize currentOffset=_currentOffset;
@property(readonly, nonatomic) struct CGPoint displayOffset;
- (void)_notifyObserversForMovementDirection:(struct CGVector)arg1;	// IMP=0x000000000061a8e3
- (void)removeObserver:(id)arg1;	// IMP=0x000000000061a8cd
- (void)addObserver:(id)arg1;	// IMP=0x000000000061a863
- (void)cancelRollbackAnimation;	// IMP=0x000000000061a825
- (void)startRollbackAnimation;	// IMP=0x000000000061a670
- (void)reset;	// IMP=0x000000000061a5dd
- (void)resetDisplayOffsetAccumulationFactor;	// IMP=0x000000000061a5c9
- (void)adjustDisplayOffsetAccumulationFactorForFocusTransfer;	// IMP=0x000000000061a5b5
- (void)updateCurrentOffset:(struct CGPoint)arg1 overrideDisplayOffset:(id)arg2;	// IMP=0x000000000061a288
- (void)updateCurrentOffset:(struct CGPoint)arg1;	// IMP=0x000000000061a274
- (id)init;	// IMP=0x000000000061a22e

@end

