//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSHashTable;

__attribute__((visibility("hidden")))
@interface _UIFocusLinearMovementCache : NSObject
{
    double _lastUpdate;	// 8 = 0x8
    double _cooldownThreshold;	// 16 = 0x10
    NSArray *_linearItems;	// 24 = 0x18
    NSHashTable *_parentEnvironments;	// 32 = 0x20
    struct {
        unsigned int isInvalidated:1;
        unsigned int invalidateOnTimeout:1;
    } _flags;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000000792e39
- (void)invalidateFocusItemContainer:(id)arg1;	// IMP=0x0000000000792e27
- (void)focusGroupPriorityDidChange:(id)arg1;	// IMP=0x0000000000792e15
- (void)environmentDidAppear:(id)arg1;	// IMP=0x0000000000792a70
- (void)environmentWillDisappear:(id)arg1;	// IMP=0x00000000007929ea
- (void)scrollableContainerDidScroll:(id)arg1;	// IMP=0x000000000079295e
- (void)_updateParentEnvironmentIfNecessary;	// IMP=0x000000000079274b
- (void)updateCacheWithContext:(id)arg1;	// IMP=0x0000000000792552
- (id)nextItemForRequest:(id)arg1;	// IMP=0x00000000007923f6
- (void)_invalidateOnTimeout;	// IMP=0x00000000007923cf
- (void)_invalidate;	// IMP=0x00000000007923c5
- (id)initWithFocusBehavior:(id)arg1;	// IMP=0x000000000079235b

@end

