//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CADisplayLink, NSArray, NSMutableArray, NSTimer, UIPanGestureRecognizer, UIScrollView, _UIDynamicAnimationGroup, _UIDynamicValueAnimation, _UIFocusEngineJoystickGestureRecognizer, _UIFocusFastScrollingIndexBarEntry, _UIFocusFastScrollingIndexBarView, _UIFocusMovementPressGestureRecognizer, _UIRotaryGestureRecognizer;

__attribute__((visibility("hidden")))
@interface _UIFocusFastScrollingController : NSObject
{
    UIScrollView *_scrollView;	// 8 = 0x8
    UIPanGestureRecognizer *_panGesture;	// 16 = 0x10
    _UIFocusMovementPressGestureRecognizer *_arrowButtonGesture;	// 24 = 0x18
    _UIFocusMovementPressGestureRecognizer *_pageButtonGesture;	// 32 = 0x20
    _UIFocusEngineJoystickGestureRecognizer *_joystickGesture;	// 40 = 0x28
    _UIRotaryGestureRecognizer *_rotaryGesture;	// 48 = 0x30
    double _lastRotaryMilestoneAccumulatedDistance;	// 56 = 0x38
    double _rotaryAccelerationMultiplier;	// 64 = 0x40
    _Bool _rotaryModeIsFullContent;	// 72 = 0x48
    double _currentRotaryDirection;	// 80 = 0x50
    NSMutableArray *_rotaryDeltaBufferArray;	// 88 = 0x58
    double _rotaryDeltaBufferAverage;	// 96 = 0x60
    double _rotaryDeltaBufferPendingValue;	// 104 = 0x68
    long long _rotaryDeltaBufferCurrentIndex;	// 112 = 0x70
    CADisplayLink *_rotaryDeltaBufferDisplayLink;	// 120 = 0x78
    _UIDynamicValueAnimation *_animationX;	// 128 = 0x80
    _UIDynamicValueAnimation *_animationY;	// 136 = 0x88
    _UIDynamicAnimationGroup *_animationGroup;	// 144 = 0x90
    long long _style;	// 152 = 0x98
    long long _userStyle;	// 160 = 0xa0
    struct CGPoint _offsetWhenPanStarted;	// 168 = 0xa8
    CDStruct_5e2aa800 _previousPanVelocity;	// 184 = 0xb8
    double _panDeadBand;	// 200 = 0xc8
    struct CGPoint _panDeadBandTranslationAdjustment;	// 208 = 0xd0
    unsigned long long _accelerationSwipeCount;	// 224 = 0xe0
    double _accelerationMultiplier;	// 232 = 0xe8
    double _accelerationStartMultiplier;	// 240 = 0xf0
    double _accelerationLastSwipeTime;	// 248 = 0xf8
    NSArray *_displayedEntries;	// 256 = 0x100
    double _initialEdgeDigitizerLocation;	// 264 = 0x108
    long long _initialIndexEntry;	// 272 = 0x110
    long long _highlightedIndexEntry;	// 280 = 0x118
    CDStruct_5e2aa800 _initialVelocity;	// 288 = 0x120
    struct CGPoint _initialContentOffset;	// 304 = 0x130
    unsigned long long _heading;	// 320 = 0x140
    unsigned long long _allowedHeadings;	// 328 = 0x148
    CADisplayLink *_discreteButtonScrollDisplayLink;	// 336 = 0x150
    double _discreteButtonScrollProgress;	// 344 = 0x158
    CADisplayLink *_continuousButtonScrollDisplayLink;	// 352 = 0x160
    CDStruct_5e2aa800 _continuousButtonScrollAnimationVelocity;	// 360 = 0x168
    struct CGVector _pressForce;	// 376 = 0x178
    double _scrollHighlight;	// 392 = 0x188
    NSTimer *_cooldownTimer;	// 400 = 0x190
    NSTimer *_buttonScrollDelayTimer;	// 408 = 0x198
    struct {
        unsigned int isDragging:1;
        unsigned int isDecelerating:1;
        unsigned int isInTrackingMode:1;
        unsigned int isIndicatingDestination:1;
        unsigned int isAttemptingToStop:1;
        unsigned int isCancellingScrollAnimation:1;
    } _flags;	// 416 = 0x1a0
    NSArray *_indexEntries;	// 424 = 0x1a8
    _UIFocusFastScrollingIndexBarView *_indexBarView;	// 432 = 0x1b0
}

+ (id)controllerWithRequest:(id)arg1;	// IMP=0x0060000000658fda
+ (long long)_indexOfEntryNearestToScrollViewBounds:(struct CGRect)arg1 inDisplayedEntries:(id)arg2 includePlaceholders:(_Bool)arg3;	// IMP=0x0060000000658bc3
+ (_Bool)_shouldIncludePlaceholderIndexBarEntriesForScrollStyle:(long long)arg1;	// IMP=0x0060000000658bb6
+ (long long)indexOfEntryForScrollStyle:(long long)arg1 nearestToScrollViewBounds:(struct CGRect)arg2 inDisplayedEntries:(id)arg3;	// IMP=0x0060000000658b37
+ (id)indexBarViewForScrollView:(id)arg1;	// IMP=0x00600000006588dc
- (void).cxx_destruct;	// IMP=0x000000000065f205
@property(readonly, nonatomic) _UIFocusFastScrollingIndexBarView *indexBarView; // @synthesize indexBarView=_indexBarView;
@property(copy, nonatomic) NSArray *indexEntries; // @synthesize indexEntries=_indexEntries;
- (void)_updateIndexBarIndicator;	// IMP=0x000000000065f19c
- (_Bool)_shouldShowEntriesInIndexBar;	// IMP=0x000000000065f153
- (void)_buttonScrollDelayEnded;	// IMP=0x000000000065f126
- (_Bool)_cancelButtonScrollDelay;	// IMP=0x000000000065f0be
- (void)_beginButtonScrollDelayWithDuration:(double)arg1;	// IMP=0x000000000065effc
- (void)_cooldownEnded;	// IMP=0x000000000065efcf
- (void)_cancelCooldown;	// IMP=0x000000000065ef8c
- (void)_beginCooldownWithDuration:(double)arg1;	// IMP=0x000000000065eeca
- (void)_stopTrackingMode;	// IMP=0x000000000065ee7f
- (void)_startTrackingModeIfNecessary;	// IMP=0x000000000065ee34
- (_Bool)_canFastScrollWithStyle:(long long)arg1;	// IMP=0x000000000065ed07
- (void)_finishDecelerating;	// IMP=0x000000000065ecb8
- (void)_attemptToStopDueToExternalEvent:(_Bool)arg1;	// IMP=0x000000000065eb76
- (void)_stopDueToExternalEvent;	// IMP=0x000000000065eb54
- (void)_attemptToStop;	// IMP=0x000000000065eb40
- (void)_start;	// IMP=0x000000000065e880
- (void)_configureWithRequest:(id)arg1;	// IMP=0x000000000065e6a1
- (void)_hideDestinationIndicators;	// IMP=0x000000000065e652
- (void)_showDestinationIndicators;	// IMP=0x000000000065e600
- (void)_updateSoftFocusForVelocity:(CDStruct_c3b9c2ee)arg1;	// IMP=0x000000000065e506
- (void)_stopScrollingAnimation;	// IMP=0x000000000065e49c
- (void)_setContentOffset:(struct CGPoint)arg1 withVelocity:(CDStruct_c3b9c2ee)arg2;	// IMP=0x000000000065e441
- (CDStruct_c3b9c2ee)_currentScrollViewDecelerationVelocity;	// IMP=0x000000000065e3f2
- (void)_startScrollingAnimationWithVelocity:(CDStruct_c3b9c2ee)arg1 friction:(struct CGPoint)arg2;	// IMP=0x000000000065df1a
- (void)_handleAnimationGroupScrollingCompletionWithInitialVelocity:(struct CGPoint)arg1 bounces:(_Bool)arg2;	// IMP=0x000000000065dc23
- (void)_handleAnimationGroupScrollingAnimations;	// IMP=0x000000000065dae7
- (void)_endDiscreteButtonScrollGesture;	// IMP=0x000000000065da8a
- (void)_discreteButtonScrollHeartbeat:(id)arg1;	// IMP=0x000000000065d814
- (long long)_nextDiscretePageScrollIndexFromIndex:(long long)arg1 inDirection:(double)arg2;	// IMP=0x000000000065d561
- (long long)_nextDiscretePageScrollIndexFromIndex:(long long)arg1 forHeading:(unsigned long long)arg2;	// IMP=0x000000000065d532
- (void)_stopDiscreteButtonScrollDisplayLink;	// IMP=0x000000000065d495
- (void)_startDiscreteButtonScrollDisplayLink;	// IMP=0x000000000065d3ca
- (long long)_advanceToNextEntryFromIndex:(long long)arg1 alongHeading:(unsigned long long)arg2;	// IMP=0x000000000065d1ce
- (void)_startDiscreteButtonScrollGestureAlongHeading:(unsigned long long)arg1;	// IMP=0x000000000065d0ab
- (_Bool)_shouldArrowButtonInterruptPanGesture;	// IMP=0x000000000065d05e
- (_Bool)_shouldArrowButtonGestureDiscreteScroll;	// IMP=0x000000000065d018
- (void)_handlePageButtonGesture:(id)arg1;	// IMP=0x000000000065cec4
- (void)_handleJoystickGesture:(id)arg1;	// IMP=0x000000000065cc2f
- (void)_resetAllButtonGestures;	// IMP=0x000000000065cbd2
- (void)_beginDeceleratingAfterContinuousButtonScroll;	// IMP=0x000000000065cb4b
- (void)_continuousButtonScrollHeartbeat:(id)arg1;	// IMP=0x000000000065c7aa
- (void)_stopContinuousButtonScrollDisplayLink;	// IMP=0x000000000065c70d
- (void)_startContinuousButtonScrollDisplayLink;	// IMP=0x000000000065c642
- (void)_startContinuousButtonScrollAlongHeading:(unsigned long long)arg1 withVelocity:(CDStruct_c3b9c2ee)arg2 delayed:(_Bool)arg3;	// IMP=0x000000000065c56e
- (_Bool)_shouldArrowButtonGestureInstantlyAdvanceToNextEntry;	// IMP=0x000000000065c4f6
- (void)_handleArrowButtonGesture:(id)arg1;	// IMP=0x000000000065c242
- (void)_rotaryHeartbeat:(id)arg1;	// IMP=0x000000000065be6f
- (struct CGPoint)_lerpRotaryGestureAccumulatedDistanceToDigitizerLocation;	// IMP=0x000000000065be08
- (void)_updateFullContentRotaryGesture;	// IMP=0x000000000065bcef
- (void)_startFullContentRotaryGesture;	// IMP=0x000000000065bc06
- (void)_handleFullContentRotaryEnd:(id)arg1;	// IMP=0x000000000065bbb2
- (void)_handleFullContentRotaryChanged:(id)arg1;	// IMP=0x000000000065bba0
- (void)_handleFullContentRotaryBegin:(id)arg1;	// IMP=0x000000000065bb8e
- (CDStruct_c3b9c2ee)_velocityOfRotaryGesture:(id)arg1 inView:(id)arg2;	// IMP=0x000000000065bb01
- (struct CGPoint)_translationOfRotaryGesture:(id)arg1 inView:(id)arg2;	// IMP=0x000000000065ba37
- (void)_handleRotaryEnd:(id)arg1;	// IMP=0x000000000065b9db
- (struct CGPoint)_rotaryRubberbandedOffsetForTranslatedOffset:(struct CGPoint)arg1;	// IMP=0x000000000065b78b
- (struct CGPoint)_rotaryTranslatedOffsetForCurrentOffset:(struct CGPoint)arg1 translation:(struct CGPoint)arg2;	// IMP=0x000000000065b764
- (void)_updateRotaryAcceleration:(id)arg1;	// IMP=0x000000000065b505
- (void)_handleRotaryChanged:(id)arg1;	// IMP=0x000000000065b354
- (_Bool)_updateRotaryDirection:(id)arg1;	// IMP=0x000000000065b2c9
- (void)_handleRotaryBegin:(id)arg1;	// IMP=0x000000000065b006
- (void)_handleCommonRotaryBegin:(id)arg1;	// IMP=0x000000000065afcb
- (void)_handleRotaryGesture:(id)arg1;	// IMP=0x000000000065adcf
- (void)_resetPanDeadBand;	// IMP=0x000000000065ad2a
- (_Bool)_isPanDeadBandActive;	// IMP=0x000000000065acb8
- (struct CGPoint)_applyPanDeadbandToTranslation:(struct CGPoint)arg1 withVelocity:(CDStruct_c3b9c2ee)arg2 inScrollView:(id)arg3;	// IMP=0x000000000065a9fb
- (void)_resetSwipeAcceleration;	// IMP=0x000000000065a9d5
- (void)_endDraggingWithFinalVelocity:(CDStruct_c3b9c2ee)arg1;	// IMP=0x000000000065a201
- (void)_beginInitialSwipeDeceleration;	// IMP=0x000000000065a1b8
- (void)_handleSwipePanEnd:(id)arg1;	// IMP=0x000000000065a157
- (void)_handleSwipePanChanged:(id)arg1;	// IMP=0x0000000000659c1b
- (void)_handleSwipePanBegin:(id)arg1;	// IMP=0x0000000000659b18
- (_Bool)_canFastScrollWithEdgeSwipe;	// IMP=0x0000000000659ab0
- (void)_interpretDigitzerLocation:(struct CGPoint)arg1 toFindEntryIndex:(long long *)arg2 deflection:(double *)arg3;	// IMP=0x00000000006598e1
- (void)_updateEdgeGesture;	// IMP=0x0000000000659800
- (void)_startEdgeGesture;	// IMP=0x0000000000659728
- (void)_handleEdgePanEnd:(id)arg1;	// IMP=0x00000000006596d4
- (void)_handleEdgePanChanged:(id)arg1;	// IMP=0x00000000006596c2
- (void)_handleEdgePanBegin:(id)arg1;	// IMP=0x00000000006596b0
- (void)_handlePanEnd:(id)arg1;	// IMP=0x000000000065965c
- (void)_handlePanChanged:(id)arg1;	// IMP=0x0000000000659608
- (long long)_panFastScrollStyleFromGesture:(id)arg1;	// IMP=0x0000000000659570
- (void)_handlePanBegin:(id)arg1 withStyle:(long long)arg2;	// IMP=0x00000000006594e6
- (void)_handlePanGesture:(id)arg1;	// IMP=0x000000000065941d
- (long long)indexOfEntryNearestToScrollViewBounds:(struct CGRect)arg1 inDisplayedEntries:(id)arg2;	// IMP=0x0000000000659390
- (unsigned long long)currentHeading;	// IMP=0x00000000006591da
@property(readonly, nonatomic) struct CGPoint initialContentOffset;
@property(readonly, nonatomic) _UIFocusFastScrollingIndexBarEntry *highlightedEntry;
@property(readonly, nonatomic) long long userScrollingStyle;
@property(readonly, nonatomic) long long scrollingStyle;
@property(readonly, nonatomic, getter=isScrollingY) _Bool scrollingY;
@property(readonly, nonatomic, getter=isScrollingX) _Bool scrollingX;
@property(readonly, nonatomic, getter=isDecelerating) _Bool decelerating;
@property(readonly, nonatomic, getter=isDragging) _Bool dragging;
- (void)stop;	// IMP=0x00000000006590f3
- (void)start;	// IMP=0x00000000006590e1
@property(readonly, nonatomic) __weak UIScrollView *scrollView;
- (id)initWithRequest:(id)arg1;	// IMP=0x0000000000658f51

@end

