//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusActiveSceneObserver_KeyboardEventDeferring
{
}

- (_Bool)isActive;	// IMP=0x0000000000156870
- (void)_activeStateChanged:(id)arg1;	// IMP=0x000000000015685e
- (void)dealloc;	// IMP=0x00000000001567e9
- (id)_initWithScene:(id)arg1;	// IMP=0x00000000001566e5

@end

