//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIScene;

__attribute__((visibility("hidden")))
@interface _UIFocusActiveSceneObserver
{
    UIScene *_scene;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000000001566d4
- (void)stopMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x00000000001566ce
- (void)beginMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x00000000001566c8
- (id)_initWithScene:(id)arg1;	// IMP=0x0000000000156685
- (id)initWithScene:(id)arg1;	// IMP=0x000000000015650c
- (id)init;	// IMP=0x00000000001564f8

@end

