//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface UIFocusRingStyle : NSObject
{
}

+ (double)animationSpeed;	// IMP=0x0080000001203906
+ (double)animationTruncationDuration;	// IMP=0x00800000012038f8
+ (double)animationActualDuration;	// IMP=0x00800000012038ea
+ (double)animationConfiguredDuration;	// IMP=0x00800000012038dc
+ (double)alphaThreshold;	// IMP=0x00800000012038ce
+ (double)maxAlpha;	// IMP=0x00800000012038c0
+ (double)minAlpha;	// IMP=0x00800000012038b7
+ (double)childrenFocusedBorderThickness;	// IMP=0x00800000012038a9
+ (double)borderThickness;	// IMP=0x008000000120389b
+ (double)cornerRadius;	// IMP=0x008000000120388d
+ (double)maxRadius;	// IMP=0x008000000120387f
+ (double)minRadius;	// IMP=0x0080000001203871

@end

