//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable, NSString, NSTimer, UIScrollView, _UIFocusEnginePanGestureRecognizer, _UIFocusFastScrollingTouchSequence, _UIRotaryGestureRecognizer;
@protocol _UIFocusFastScrollingRecognizerDelegate;

__attribute__((visibility("hidden")))
@interface _UIFocusFastScrollingRecognizer : NSObject
{
    _UIFocusEnginePanGestureRecognizer *_panGesture;	// 8 = 0x8
    _UIRotaryGestureRecognizer *_rotaryGesture;	// 16 = 0x10
    _UIFocusFastScrollingTouchSequence *_currentTouch;	// 24 = 0x18
    NSMapTable *_swipeSequences;	// 32 = 0x20
    NSTimer *_swipeIntervalTimer;	// 40 = 0x28
    UIScrollView *_previewingScrollView;	// 48 = 0x30
    NSTimer *_previewingTouchTimer;	// 56 = 0x38
    unsigned long long _spatialFocusUpdateCount;	// 64 = 0x40
    _Bool _persistFastScrollingPreviewThroughReset;	// 72 = 0x48
    double _rotaryMovementSequenceLastUpdateTime;	// 80 = 0x50
    long long _rotaryMovementSequenceCount;	// 88 = 0x58
    unsigned long long _rotaryMovementSequenceHeading;	// 96 = 0x60
    _Bool _enabled;	// 104 = 0x68
    id <_UIFocusFastScrollingRecognizerDelegate> _delegate;	// 112 = 0x70
}

- (void).cxx_destruct;	// IMP=0x00000000007595b5
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) __weak id <_UIFocusFastScrollingRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)focusEnginePanGesture:(id)arg1 touchCancelledAtDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x0000000000759537
- (void)focusEnginePanGesture:(id)arg1 touchEndedAtDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x00000000007594e9
- (void)focusEnginePanGesture:(id)arg1 touchMovedToDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x000000000075947f
- (void)focusEnginePanGesture:(id)arg1 touchBeganAtDigitizerLocation:(struct CGPoint)arg2;	// IMP=0x0000000000759415
- (void)_deactivatePreviewingScrollViewIfNecessary;	// IMP=0x00000000007593ad
- (void)_activatePreviewingScrollViewForScrollingStyle:(long long)arg1 emphasisAnimation:(_Bool)arg2 overrideIndexDisplayMode:(_Bool)arg3;	// IMP=0x00000000007592f3
- (void)_activatePreviewingScrollViewForEdgeGesture;	// IMP=0x00000000007592d7
- (void)_activatePreviewingScrollViewForEdgeGestureAfterDelay;	// IMP=0x0000000000759275
- (void)_notifyDelegateWithScrollView:(id)arg1 scrollingStyle:(long long)arg2 heading:(unsigned long long)arg3 initiationMode:(long long)arg4;	// IMP=0x000000000075914c
- (void)_notifyDelegateWithScrollView:(id)arg1 scrollingStyle:(long long)arg2 heading:(unsigned long long)arg3;	// IMP=0x0000000000759137
- (_Bool)_scrollViewIsEligibleForFastScrolling:(id)arg1 alongHeading:(unsigned long long)arg2 withScrollingStyle:(long long)arg3;	// IMP=0x0000000000758fc5
- (id)_scrollViewsContainingCurrentlyFocusedItem;	// IMP=0x0000000000758c79
- (_Bool)_attemptToImmediatelyRecognizeEdgeGesture;	// IMP=0x0000000000758ab2
- (id)_deepestEligibleScrollViewContainingFocusedItem:(unsigned long long)arg1 withScrollingStyle:(long long)arg2;	// IMP=0x000000000075891d
- (_Bool)_canFastScrollWithEdgeSwipe;	// IMP=0x00000000007588b5
- (_Bool)_swipeSequenceCanBeginFastScrolling:(id)arg1;	// IMP=0x0000000000758865
- (void)_updateActiveSwipeSequencesForScrollViews:(id)arg1;	// IMP=0x0000000000758451
- (unsigned long long)_bestHeadingForAccumulator:(struct CGVector)arg1;	// IMP=0x00000000007582f0
- (void)_swipeIntervalElapsed:(id)arg1;	// IMP=0x00000000007582de
- (void)_stopSwipeIntervalTimer;	// IMP=0x00000000007582ad
- (void)_startSwipeIntervalTimer;	// IMP=0x00000000007581d7
- (void)_swipeOccuredAlongHeading:(unsigned long long)arg1;	// IMP=0x0000000000757aa6
- (void)_touchSequenceDidEnd:(id)arg1;	// IMP=0x00000000007578e7
- (void)_resetRotaryMovementSequence;	// IMP=0x00000000007578d2
- (void)reset;	// IMP=0x00000000007576e0
- (void)_handlePanGesture:(id)arg1;	// IMP=0x00000000007572c2
- (void)_handleRotaryFocusDidMoveWithHeading:(unsigned long long)arg1;	// IMP=0x00000000007570c7
- (void)focusDidMoveWithHeading:(unsigned long long)arg1 inputType:(unsigned long long)arg2;	// IMP=0x00000000007570a7
- (void)fastScrollingIndexBarWasFocusedInScrollView:(id)arg1;	// IMP=0x0000000000757082
- (void)pageButtonPressWithHeading:(unsigned long long)arg1 didRepeat:(unsigned long long)arg2;	// IMP=0x0000000000757012
- (void)joystickMovementWithHeading:(unsigned long long)arg1 didRepeat:(unsigned long long)arg2;	// IMP=0x0000000000756f93
- (void)directionalPressWithHeading:(unsigned long long)arg1 didRepeat:(unsigned long long)arg2;	// IMP=0x0000000000756ee2
- (void)_focusDidUpate:(id)arg1;	// IMP=0x0000000000756b98
- (void)dealloc;	// IMP=0x0000000000756adb
- (id)initWithPanGesture:(id)arg1 rotaryGesture:(id)arg2;	// IMP=0x0000000000756a7c
- (id)initWithPanGesture:(id)arg1;	// IMP=0x000000000075697f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

