//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString, UIView;
@protocol UICoordinateSpace, UIFocusItem;

__attribute__((visibility("hidden")))
@interface _UIFocusGroup : NSObject
{
    struct {
        unsigned int itemOrderValid:1;
        unsigned int childGroupOrderValid:1;
        unsigned int primaryItemValid:1;
        unsigned int primaryRectValid:1;
    } _flags;	// 8 = 0x8
    NSMutableArray *_childGroups;	// 16 = 0x10
    NSMutableArray *_items;	// 24 = 0x18
    id <UIFocusItem> _primaryItem;	// 32 = 0x20
    NSString *_identifier;	// 40 = 0x28
    _UIFocusGroup *_parentGroup;	// 48 = 0x30
    id <UICoordinateSpace> _coordinateSpace;	// 56 = 0x38
    UIView *_owningView;	// 64 = 0x40
    struct CGRect _primaryRect;	// 72 = 0x48
    struct CGRect _boundingBox;	// 104 = 0x68
}

+ (id)nullGroupWithCoordinateSpace:(id)arg1;	// IMP=0x0060000000c805bf
- (void).cxx_destruct;	// IMP=0x0000000000c816c2
@property(readonly, nonatomic, getter=_owningView) UIView *owningView; // @synthesize owningView=_owningView;
@property(readonly, nonatomic) id <UICoordinateSpace> coordinateSpace; // @synthesize coordinateSpace=_coordinateSpace;
@property(readonly, nonatomic) struct CGRect boundingBox; // @synthesize boundingBox=_boundingBox;
@property(readonly, nonatomic) __weak _UIFocusGroup *parentGroup; // @synthesize parentGroup=_parentGroup;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)childGroupWithIdentifier:(id)arg1;	// IMP=0x0000000000c815c2
- (id)initWithIdentifier:(id)arg1;	// IMP=0x0000000000c81521
- (id)debugDescription;	// IMP=0x0000000000c81431
- (id)description;	// IMP=0x0000000000c8137c
- (_Bool)isEqualToFocusGroup:(id)arg1;	// IMP=0x0000000000c81362
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000000c812f6
- (unsigned long long)hash;	// IMP=0x0000000000c812e0
- (void)_validatePrimaryRectIfNeccessary;	// IMP=0x0000000000c810d5
- (void)_invalidatePrimaryRect;	// IMP=0x0000000000c810cb
- (void)_validatePrimaryItemIfNecessary;	// IMP=0x0000000000c80e69
- (void)_invalidatePrimaryItem;	// IMP=0x0000000000c80e53
- (void)_validateChildGroupOrderIfNecessary;	// IMP=0x0000000000c80df3
- (void)_invalidateChildGroupOrder;	// IMP=0x0000000000c80ddd
- (void)_validateItemOrderIfNecessary;	// IMP=0x0000000000c80d7d
- (void)_invalidateItemOrder;	// IMP=0x0000000000c80d67
@property(readonly, nonatomic) struct CGRect primaryRect; // @synthesize primaryRect=_primaryRect;
@property(readonly, nonatomic) id <UIFocusItem> primaryItem; // @synthesize primaryItem=_primaryItem;
@property(readonly, nonatomic) NSArray *items;
@property(readonly, nonatomic) NSArray *childGroups;
- (void)_updateWithEnvironment:(id)arg1;	// IMP=0x0000000000c80bc5
- (void)_insertItem:(id)arg1;	// IMP=0x0000000000c80b93
- (void)_insertChildGroup:(id)arg1;	// IMP=0x0000000000c80b61
- (id)_deepCopyWithNewIdentifierToGroupMap:(id)arg1;	// IMP=0x0000000000c8085a
- (id)initWithIdentifier:(id)arg1 parentGroup:(id)arg2 coordinateSpace:(id)arg3;	// IMP=0x0000000000c80615

@end

