//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_CarPlayTouchpad
{
}

+ (id)sharedInstance;	// IMP=0x008000000020fb7a
- (_Bool)refinesIndexBarTargetContentOffset;	// IMP=0x000000000020fc0f
- (_Bool)shouldEnableFocusOnSelect;	// IMP=0x000000000020fc07
- (_Bool)supportsIndirectPanningMovement;	// IMP=0x000000000020fbff

@end

