//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIGestureRecognizer.h"

__attribute__((visibility("hidden")))
@interface _UIFocusEngineJoystickGestureRecognizer : UIGestureRecognizer
{
    struct CGPoint _stickPosition;	// 8 = 0x8
    struct CGPoint _previousStickPosition;	// 24 = 0x18
}

@property(readonly, nonatomic) struct CGPoint previousStickPosition; // @synthesize previousStickPosition=_previousStickPosition;
@property(readonly, nonatomic) struct CGPoint stickPosition; // @synthesize stickPosition=_stickPosition;
- (void)_calculateStickPositionFromPresses:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000000006fb19f
- (void)reset;	// IMP=0x00000000006fb199
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000000006fb12e
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000000006fb0c3
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000000006fb058
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000000006fafed
- (_Bool)_shouldReceivePress:(id)arg1;	// IMP=0x00000000006faf9b
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x00000000006faf47

@end

