//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PrototypeTools/PTDomain.h>

__attribute__((visibility("hidden")))
@interface _UIFocusSettingsDomain : PTDomain
{
}

+ (Class)rootSettingsClass;	// IMP=0x00800000010efa81
+ (id)domainName;	// IMP=0x00800000010efa74
+ (id)domainGroupName;	// IMP=0x00800000010efa67
+ (id)rootSettings;	// IMP=0x00800000010efa29

@end

