//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_FKA : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00100000006aa060
- (_Bool)supportsLinearMovementDebugOverlay;	// IMP=0x00000000006aa3db
- (_Bool)shouldCallAccessibilityOverrides;	// IMP=0x00000000006aa3d3
- (long long)focusSystemDeactivationMode;	// IMP=0x00000000006aa3cb
- (_Bool)autoDismissesPopoverControllersOnFocusIntersection;	// IMP=0x00000000006aa3c3
- (_Bool)tabBasedMovementLoops;	// IMP=0x00000000006aa3bb
- (long long)skipKeyCommandsForKeyEvents;	// IMP=0x00000000006aa3b3
- (long long)deliverKeyEventsToFocusEngine;	// IMP=0x00000000006aa3ab
- (_Bool)shouldSupressIndirectMovementOnSelect;	// IMP=0x00000000006aa3a3
- (_Bool)shouldEnableFocusOnSelect;	// IMP=0x00000000006aa39b
- (long long)pageButtonScrollingStyle;	// IMP=0x00000000006aa393
- (_Bool)supportsArrowKeys;	// IMP=0x00000000006aa38b
- (_Bool)supportsGameControllers;	// IMP=0x00000000006aa340
- (_Bool)shouldConvertIndirectTapsIntoArrowKeys;	// IMP=0x00000000006aa338
- (_Bool)supportsIndirectRotaryMovement;	// IMP=0x00000000006aa330
- (_Bool)supportsIndirectPanningMovement;	// IMP=0x00000000006aa328
- (_Bool)showsFocusRingForItem:(id)arg1;	// IMP=0x00000000006aa320
- (_Bool)supportsParentFocusRings;	// IMP=0x00000000006aa318
- (long long)focusRingVisibility;	// IMP=0x00000000006aa30d
- (long long)buttonSelectionMode;	// IMP=0x00000000006aa305
- (_Bool)refinesIndexBarTargetContentOffset;	// IMP=0x00000000006aa2fd
- (_Bool)isContainerEligibleForFocusUpdateSearchRoot:(id)arg1;	// IMP=0x00000000006aa245
- (double)stabilizedLinearFocusMovementTimeout;	// IMP=0x00000000006aa23c
- (_Bool)wantsTreeLocking;	// IMP=0x00000000006aa234
- (_Bool)throttlesProgrammaticFocusUpdates;	// IMP=0x00000000006aa22c
- (long long)focusCastingMode;	// IMP=0x00000000006aa224
- (_Bool)supportsClipToBounds;	// IMP=0x00000000006aa210
- (_Bool)supportViewTransparencyAndMultipleWindows;	// IMP=0x00000000006aa1fc
- (_Bool)treatFirstAndLastHeadingsAsGlobal;	// IMP=0x00000000006aa1f4
- (_Bool)defaultValueForSelectionFollowsFocusInTableView:(id)arg1;	// IMP=0x00000000006aa1ec
- (_Bool)defaultValueForSelectionFollowsFocusInCollectionView:(id)arg1;	// IMP=0x00000000006aa1e4
- (_Bool)preventsCellFocusabilityWhileEditing;	// IMP=0x00000000006aa1dc
- (long long)cellFocusability;	// IMP=0x00000000006aa1d4
- (_Bool)shouldUseAccessibilityCompareForFocusGroupsInExternallyPlacedWindows;	// IMP=0x00000000006aa1cc
- (_Bool)shouldUseAccessibilityCompareForItemGeometry;	// IMP=0x00000000006aa1c4
- (long long)scrollingMode;	// IMP=0x00000000006aa1b9
- (unsigned long long)defaultFocusScrollOffsetResolver;	// IMP=0x00000000006aa1ae
- (_Bool)enforcesStrictTargetContentOffsetAdjustmentBehavior;	// IMP=0x00000000006aa1a6
- (unsigned long long)focusGroupContainmentBehavior;	// IMP=0x00000000006aa19b
- (unsigned long long)focusGroupMovementBehavior;	// IMP=0x00000000006aa190
- (long long)indirectMovementPriority;	// IMP=0x00000000006aa188
- (_Bool)supportsTabKey;	// IMP=0x00000000006aa180
- (_Bool)includesContentScrollViewInPreferredFocusEnvironments;	// IMP=0x00000000006aa178
- (_Bool)searchBarTextFieldCanBecomeFocused;	// IMP=0x00000000006aa170
- (_Bool)tabBarButtonCanBecomeFocused;	// IMP=0x00000000006aa168
- (_Bool)tabBarCanBecomeFocused;	// IMP=0x00000000006aa160
- (_Bool)textViewCanBecomeFocused:(id)arg1;	// IMP=0x00000000006aa14b
- (_Bool)controlCanBecomeFocused:(id)arg1;	// IMP=0x00000000006aa143
- (_Bool)ignoresKeyWindowStatusWhenRestoringFocus;	// IMP=0x00000000006aa13b
- (long long)focusDeferral;	// IMP=0x00000000006aa133
- (_Bool)syncsFocusAndResponder;	// IMP=0x00000000006aa12b
- (long long)requiredInputDevices;	// IMP=0x00000000006aa0f5
- (_Bool)honorsFocusSystemEnabledInfoPlistKey;	// IMP=0x00000000006aa0ed
- (_Bool)wantsFocusSystemForScene:(id)arg1;	// IMP=0x00000000006aa0e5

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

