//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_CarPlayTouch
{
}

+ (id)sharedInstance;	// IMP=0x0080000001243de9
- (_Bool)searchBarTextFieldCanBecomeFocused;	// IMP=0x0000000001243f1a
- (long long)focusDeferral;	// IMP=0x0000000001243e6e

@end

