//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, UIScreen, _UIFocusDisplayLinkScrollAnimator;

__attribute__((visibility("hidden")))
@interface _UIFocusScrollManager : NSObject
{
    UIScreen *_screen;	// 8 = 0x8
    _UIFocusDisplayLinkScrollAnimator *_scrollAnimator;	// 16 = 0x10
    NSHashTable *_stackVisitedScrollingContainers;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000000007616f7
@property(readonly, nonatomic) NSHashTable *stackVisitedScrollingContainers; // @synthesize stackVisitedScrollingContainers=_stackVisitedScrollingContainers;
@property(readonly, nonatomic) _UIFocusDisplayLinkScrollAnimator *scrollAnimator; // @synthesize scrollAnimator=_scrollAnimator;
@property(readonly, nonatomic) __weak UIScreen *screen; // @synthesize screen=_screen;
- (void)_ensureFocusItemIsOnscreenForScrollRequest:(id)arg1;	// IMP=0x00000000007613a1
- (_Bool)_scrollWithScrollRequest:(id)arg1 onlyIfNecessary:(_Bool)arg2;	// IMP=0x0000000000760ba2
- (void)adjustTargetContentOffsetForScrollableContainer:(id)arg1 byDelta:(struct CGPoint)arg2;	// IMP=0x0000000000760b8c
- (struct CGPoint)contentOffsetForEnvironmentScrollableContainer:(id)arg1 toShowRect:(struct CGRect)arg2 targetOffset:(struct CGPoint)arg3;	// IMP=0x0000000000760ab1
- (struct CGPoint)contentOffsetForEnvironmentScrollableContainer:(id)arg1 toShowFocusItem:(id)arg2 targetOffset:(struct CGPoint)arg3;	// IMP=0x00000000007609b1
- (void)animateOffsetOfScrollableContainersInParentEnvironmentContainer:(id)arg1 toShowFocusItem:(id)arg2;	// IMP=0x0000000000760777
- (void)animateOffsetOfEnvironmentScrollableContainer:(id)arg1 toShowFocusItem:(id)arg2;	// IMP=0x0000000000760660
- (struct CGPoint)currentVelocityForScrollableContainer:(id)arg1;	// IMP=0x000000000076064a
- (struct CGPoint)targetContentOffsetForScrollableContainer:(id)arg1;	// IMP=0x00000000007605c6
- (void)cancelScrollingForScrollableContainer:(id)arg1;	// IMP=0x00000000007605b0
- (_Bool)isScrollingScrollableContainer:(id)arg1;	// IMP=0x000000000076059a
- (void)performScrollingIfNeededForFocusUpdateInContext:(id)arg1;	// IMP=0x000000000075fe1d
- (id)initWithScreen:(id)arg1;	// IMP=0x000000000075fc9f

@end

