//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, _UIDynamicValueConvergenceAnimation;

__attribute__((visibility("hidden")))
@interface _UIFocusEffectsController : NSObject
{
    _UIDynamicValueConvergenceAnimation *_rollbackAnimation;	// 8 = 0x8
    NSHashTable *_observers;	// 16 = 0x10
    struct CGPoint _displayOffset;	// 24 = 0x18
    double _displayMovementAdjustment;	// 40 = 0x28
    _Bool _displayOffsetAccumulatorEnabled;	// 48 = 0x30
    struct CGPoint _currentOffset;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000000707b81
@property(nonatomic) _Bool displayOffsetAccumulatorEnabled; // @synthesize displayOffsetAccumulatorEnabled=_displayOffsetAccumulatorEnabled;
@property(readonly, nonatomic) struct CGPoint currentOffset; // @synthesize currentOffset=_currentOffset;
@property(readonly, nonatomic) struct CGPoint displayOffset;
- (void)_notifyObserversForMovementDirection:(struct CGVector)arg1;	// IMP=0x00000000007079f0
- (void)removeObserver:(id)arg1;	// IMP=0x00000000007079da
- (void)addObserver:(id)arg1;	// IMP=0x0000000000707970
- (void)cancelRollbackAnimation;	// IMP=0x0000000000707932
- (void)startRollbackAnimation;	// IMP=0x000000000070777d
- (void)reset;	// IMP=0x00000000007076ea
- (void)resetDisplayOffsetAccumulationFactor;	// IMP=0x00000000007076d6
- (void)adjustDisplayOffsetAccumulationFactorForFocusTransfer;	// IMP=0x00000000007076c2
- (void)updateCurrentOffset:(struct CGPoint)arg1 overrideDisplayOffset:(id)arg2;	// IMP=0x00000000007073e9
- (void)updateCurrentOffset:(struct CGPoint)arg1;	// IMP=0x00000000007073d5
- (id)init;	// IMP=0x000000000070738f

@end

