//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSURL;

__attribute__((visibility("hidden")))
@interface _UIFocusSoundPool : NSObject
{
    NSURL *_soundFileURL;	// 8 = 0x8
    unsigned int _originalSystemSoundID;	// 16 = 0x10
    NSArray *_queue;	// 24 = 0x18
    unsigned long long _queueIndex;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000000073c4a7
- (unsigned int)originalSystemSoundID;	// IMP=0x000000000073c49e
- (unsigned int)playableSystemSoundID;	// IMP=0x000000000073c0f7
- (id)initWithSoundFileURL:(id)arg1;	// IMP=0x000000000073c084
- (id)initWithSystemSoundID:(unsigned int)arg1;	// IMP=0x000000000073c041

@end

