//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIView.h"

@class CAShapeLayer;

__attribute__((visibility("hidden")))
@interface _UIFocusRotaryRingArrowView : UIView
{
    CAShapeLayer *_shapeLayer;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000000014a5039
- (id)_trianglePath;	// IMP=0x00000000014a4ef9
- (void)_updateShapePath;	// IMP=0x00000000014a4e90
- (void)updateArrowColor:(id)arg1;	// IMP=0x00000000014a4e4c
- (void)layoutSubviews;	// IMP=0x00000000014a4e0b
- (id)initWithFrame:(struct CGRect)arg1 color:(id)arg2;	// IMP=0x00000000014a4d06

@end

