//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface _UIFocusBehavior_TV : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00100000012ceb1f
- (_Bool)supportsLinearMovementDebugOverlay;	// IMP=0x00000000012cf069
- (_Bool)shouldCallAccessibilityOverrides;	// IMP=0x00000000012cf061
- (void)_handleRemoteTouchSurfaceTypeDidChangeNotification:(id)arg1;	// IMP=0x00000000012cf011
- (long long)focusSystemDeactivationMode;	// IMP=0x00000000012cf006
- (_Bool)autoDismissesPopoverControllersOnFocusIntersection;	// IMP=0x00000000012ceffe
- (_Bool)tabBasedMovementLoops;	// IMP=0x00000000012ceff6
- (long long)skipKeyCommandsForKeyEvents;	// IMP=0x00000000012cefee
- (long long)deliverKeyEventsToFocusEngine;	// IMP=0x00000000012cefe3
- (_Bool)shouldSupressIndirectMovementOnSelect;	// IMP=0x00000000012cefd9
- (_Bool)shouldEnableFocusOnSelect;	// IMP=0x00000000012cefd1
- (long long)indirectMovementPriority;	// IMP=0x00000000012cef93
- (_Bool)supportsTabKey;	// IMP=0x00000000012cef8b
- (long long)pageButtonScrollingStyle;	// IMP=0x00000000012cef36
- (_Bool)supportsArrowKeys;	// IMP=0x00000000012cef2e
- (_Bool)supportsGameControllers;	// IMP=0x00000000012cef26
- (_Bool)shouldConvertIndirectTapsIntoArrowKeys;	// IMP=0x00000000012cef02
- (_Bool)supportsIndirectRotaryMovement;	// IMP=0x00000000012cee1a
- (_Bool)supportsIndirectPanningMovement;	// IMP=0x00000000012cee12
- (_Bool)showsFocusRingForItem:(id)arg1;	// IMP=0x00000000012cee0a
- (_Bool)supportsParentFocusRings;	// IMP=0x00000000012cee02
- (long long)focusRingVisibility;	// IMP=0x00000000012cedfa
- (long long)buttonSelectionMode;	// IMP=0x00000000012cedef
- (_Bool)refinesIndexBarTargetContentOffset;	// IMP=0x00000000012cede7
- (_Bool)isContainerEligibleForFocusUpdateSearchRoot:(id)arg1;	// IMP=0x00000000012cedd2
- (double)stabilizedLinearFocusMovementTimeout;	// IMP=0x00000000012cedc4
- (_Bool)wantsTreeLocking;	// IMP=0x00000000012cedbc
- (_Bool)throttlesProgrammaticFocusUpdates;	// IMP=0x00000000012cedb4
- (long long)focusCastingMode;	// IMP=0x00000000012ceda9
- (_Bool)supportsClipToBounds;	// IMP=0x00000000012ced95
- (_Bool)supportViewTransparencyAndMultipleWindows;	// IMP=0x00000000012ced8d
- (_Bool)treatFirstAndLastHeadingsAsGlobal;	// IMP=0x00000000012ced85
- (_Bool)defaultValueForSelectionFollowsFocusInTableView:(id)arg1;	// IMP=0x00000000012ced7d
- (_Bool)defaultValueForSelectionFollowsFocusInCollectionView:(id)arg1;	// IMP=0x00000000012ced75
- (_Bool)preventsCellFocusabilityWhileEditing;	// IMP=0x00000000012ced6d
- (long long)cellFocusability;	// IMP=0x00000000012ced65
- (_Bool)shouldUseAccessibilityCompareForFocusGroupsInExternallyPlacedWindows;	// IMP=0x00000000012ced5d
- (_Bool)shouldUseAccessibilityCompareForItemGeometry;	// IMP=0x00000000012ced55
- (long long)scrollingMode;	// IMP=0x00000000012ced4d
- (unsigned long long)defaultFocusScrollOffsetResolver;	// IMP=0x00000000012ced45
- (_Bool)enforcesStrictTargetContentOffsetAdjustmentBehavior;	// IMP=0x00000000012ced3d
- (unsigned long long)focusGroupContainmentBehavior;	// IMP=0x00000000012ced32
- (unsigned long long)focusGroupMovementBehavior;	// IMP=0x00000000012ced27
- (_Bool)includesContentScrollViewInPreferredFocusEnvironments;	// IMP=0x00000000012ced1f
- (_Bool)searchBarTextFieldCanBecomeFocused;	// IMP=0x00000000012ced17
- (_Bool)tabBarButtonCanBecomeFocused;	// IMP=0x00000000012ced0f
- (_Bool)tabBarCanBecomeFocused;	// IMP=0x00000000012ced07
- (_Bool)textViewCanBecomeFocused:(id)arg1;	// IMP=0x00000000012cecf2
- (_Bool)controlCanBecomeFocused:(id)arg1;	// IMP=0x00000000012cecea
- (_Bool)ignoresKeyWindowStatusWhenRestoringFocus;	// IMP=0x00000000012cece2
- (long long)focusDeferral;	// IMP=0x00000000012cecda
- (_Bool)syncsFocusAndResponder;	// IMP=0x00000000012cecd2
- (long long)requiredInputDevices;	// IMP=0x00000000012cecca
- (_Bool)honorsFocusSystemEnabledInfoPlistKey;	// IMP=0x00000000012cecc2
- (_Bool)wantsFocusSystemForScene:(id)arg1;	// IMP=0x00000000012cecba
- (void)dealloc;	// IMP=0x00000000012cec38
- (id)init;	// IMP=0x00000000012ceba4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

