//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol _UIFocusMovementPerformerDelegate;

__attribute__((visibility("hidden")))
@interface _UIFocusMovementPerformer : NSObject
{
    id <_UIFocusMovementPerformerDelegate> _delegate;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000000073b65e
@property(nonatomic) __weak id <_UIFocusMovementPerformerDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)_minimumSearchAreaForContainer:(id)arg1 inWindow:(id)arg2 shouldLoadScrollableContainer:(_Bool)arg3;	// IMP=0x000000000073b35b
- (struct CGRect)_minimumSearchAreaForContainer:(id)arg1 inWindow:(id)arg2;	// IMP=0x000000000073b336
- (_Bool)_isMovementValidForFocusSequences:(id)arg1;	// IMP=0x000000000073aff0
- (id)_nextLinearCandidateLoadingScrollableContentForRequest:(id)arg1;	// IMP=0x000000000073a1f2
- (id)_fakeFocusedViewForFocusMovement:(id)arg1 searchArea:(struct CGRect)arg2 window:(id)arg3;	// IMP=0x000000000073a076
- (id)_environmentContainersToCheckForRequest:(id)arg1;	// IMP=0x0000000000739910
- (id)_bestCandidateForFocusMovement:(id)arg1;	// IMP=0x0000000000739863
- (id)_bestCandidateForLinearFocusMovement:(id)arg1;	// IMP=0x000000000073963a
- (id)_bestCandidateForNonLinearFocusMovement:(id)arg1;	// IMP=0x0000000000738e65
- (id)_findFocusCandidateBySearchingLinearFocusMovementSequencesForRequest:(id)arg1;	// IMP=0x0000000000738856
- (id)_findFocusCandidateByExhaustivelySearchingEnvironment:(id)arg1 scrollableContainer:(id)arg2 forRequest:(id)arg3;	// IMP=0x0000000000737eba
- (_Bool)_shouldRecordDestinationItemDistanceOffscreenInWindow:(id)arg1;	// IMP=0x0000000000737e6e
- (id)_findFocusCandidateWithoutLoadingScrollableContentInEnvironment:(id)arg1 container:(id)arg2 forRequest:(id)arg3 minimumSearchArea:(struct CGRect)arg4;	// IMP=0x0000000000737e59
- (id)__findFocusCandidateInEnvironment:(id)arg1 container:(id)arg2 forRequest:(id)arg3 minimumSearchArea:(struct CGRect)arg4 isLoadingScrollableContainer:(_Bool)arg5;	// IMP=0x0000000000737be6
- (id)viewForFocusHeading:(unsigned long long)arg1 fromView:(id)arg2;	// IMP=0x00000000007379c3
- (_Bool)performFocusMovement:(id)arg1;	// IMP=0x0000000000737417

@end

