//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol _UIFocusSoundPlayer;

__attribute__((visibility("hidden")))
@interface _UIFocusSoundGenerator : NSObject
{
    id <_UIFocusSoundPlayer> _focusSoundPlayer;	// 8 = 0x8
}

+ (void)_uiktest_unregisterURLForIdentifier:(id)arg1;	// IMP=0x006000000073bf51
+ (void)registerURL:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x006000000073bd3a
+ (id)defaultGenerator;	// IMP=0x006000000073b6b8
- (void).cxx_destruct;	// IMP=0x000000000073c031
@property(readonly, nonatomic) id <_UIFocusSoundPlayer> focusSoundPlayer; // @synthesize focusSoundPlayer=_focusSoundPlayer;
- (void)playSoundForFocusUpdateInContext:(id)arg1;	// IMP=0x000000000073b78d
- (id)initWithFocusSoundPlayer:(id)arg1;	// IMP=0x000000000073b722

@end

