//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface _UIFocusDebugWindowLabelModule : UIView
{
    UILabel *_content;	// 128 = 0x80
}

- (void).cxx_destruct;	// IMP=0x0000000000db0dd9
- (void)update;	// IMP=0x0000000000db0d85
- (id)updatedAttributedLabelContent;	// IMP=0x0000000000db0d1c
- (id)updatedLabelContent;	// IMP=0x0000000000db0c8f
- (id)title;	// IMP=0x0000000000db0c82
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000000db08da

@end

