//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CADisplayLink, NSArray, NSMutableArray, NSTimer, UIPanGestureRecognizer, UIScrollView, _UIDynamicAnimationGroup, _UIDynamicValueAnimation, _UIFocusEngineJoystickGestureRecognizer, _UIFocusFastScrollingIndexBarEntry, _UIFocusFastScrollingIndexBarView, _UIFocusMovementPressGestureRecognizer, _UIRotaryGestureRecognizer;

__attribute__((visibility("hidden")))
@interface _UIFocusFastScrollingController : NSObject
{
    UIScrollView *_scrollView;	// 8 = 0x8
    UIPanGestureRecognizer *_panGesture;	// 16 = 0x10
    _UIFocusMovementPressGestureRecognizer *_arrowButtonGesture;	// 24 = 0x18
    _UIFocusMovementPressGestureRecognizer *_pageButtonGesture;	// 32 = 0x20
    _UIFocusEngineJoystickGestureRecognizer *_joystickGesture;	// 40 = 0x28
    _UIRotaryGestureRecognizer *_rotaryGesture;	// 48 = 0x30
    double _lastRotaryMilestoneAccumulatedDistance;	// 56 = 0x38
    double _rotaryAccelerationMultiplier;	// 64 = 0x40
    double _currentRotaryDirection;	// 72 = 0x48
    NSMutableArray *_rotaryDeltaBufferArray;	// 80 = 0x50
    double _rotaryDeltaBufferAverage;	// 88 = 0x58
    double _rotaryDeltaBufferPendingValue;	// 96 = 0x60
    long long _rotaryDeltaBufferCurrentIndex;	// 104 = 0x68
    CADisplayLink *_rotaryDeltaBufferDisplayLink;	// 112 = 0x70
    _UIDynamicValueAnimation *_animationX;	// 120 = 0x78
    _UIDynamicValueAnimation *_animationY;	// 128 = 0x80
    _UIDynamicAnimationGroup *_animationGroup;	// 136 = 0x88
    long long _style;	// 144 = 0x90
    long long _userStyle;	// 152 = 0x98
    long long _initiationMode;	// 160 = 0xa0
    struct CGPoint _offsetWhenPanStarted;	// 168 = 0xa8
    CDStruct_5e2aa800 _previousPanVelocity;	// 184 = 0xb8
    double _panDeadBand;	// 200 = 0xc8
    struct CGPoint _panDeadBandTranslationAdjustment;	// 208 = 0xd0
    unsigned long long _accelerationSwipeCount;	// 224 = 0xe0
    double _accelerationMultiplier;	// 232 = 0xe8
    double _accelerationStartMultiplier;	// 240 = 0xf0
    double _accelerationLastSwipeTime;	// 248 = 0xf8
    NSArray *_displayedEntries;	// 256 = 0x100
    double _initialEdgeDigitizerLocation;	// 264 = 0x108
    long long _discreteScrollingInitialIndexEntry;	// 272 = 0x110
    long long _discreteScrollingHighlightedIndexEntry;	// 280 = 0x118
    CDStruct_5e2aa800 _initialVelocity;	// 288 = 0x120
    struct CGPoint _initialContentOffset;	// 304 = 0x130
    unsigned long long _heading;	// 320 = 0x140
    unsigned long long _allowedHeadings;	// 328 = 0x148
    CADisplayLink *_discreteButtonScrollDisplayLink;	// 336 = 0x150
    double _discreteButtonScrollProgress;	// 344 = 0x158
    CADisplayLink *_continuousButtonScrollDisplayLink;	// 352 = 0x160
    CDStruct_5e2aa800 _continuousButtonScrollAnimationVelocity;	// 360 = 0x168
    struct CGVector _pressForce;	// 376 = 0x178
    double _scrollHighlight;	// 392 = 0x188
    NSTimer *_cooldownTimer;	// 400 = 0x190
    NSTimer *_buttonScrollDelayTimer;	// 408 = 0x198
    struct {
        unsigned int isDragging:1;
        unsigned int isDecelerating:1;
        unsigned int isInTrackingMode:1;
        unsigned int isIndicatingDestination:1;
        unsigned int isAttemptingToStop:1;
        unsigned int isCancellingScrollAnimation:1;
    } _flags;	// 416 = 0x1a0
    NSArray *_indexEntries;	// 424 = 0x1a8
    _UIFocusFastScrollingIndexBarView *_indexBarView;	// 432 = 0x1b0
}

+ (id)trimEntriesToFitSlotCount:(id)arg1 availableSlots:(unsigned long long)arg2;	// IMP=0x006000000075018d
+ (id)controllerWithRequest:(id)arg1;	// IMP=0x006000000074a1a9
+ (long long)_indexOfEntryNearestToScrollViewBounds:(struct CGRect)arg1 inDisplayedEntries:(id)arg2 includePlaceholders:(_Bool)arg3;	// IMP=0x0060000000749cb4
+ (_Bool)_shouldIncludePlaceholderIndexBarEntriesForScrollStyle:(long long)arg1;	// IMP=0x0060000000749ca7
+ (long long)indexOfEntryForScrollStyle:(long long)arg1 nearestToScrollViewBounds:(struct CGRect)arg2 inDisplayedEntries:(id)arg3;	// IMP=0x0060000000749c28
- (void).cxx_destruct;	// IMP=0x0000000000750280
@property(readonly, nonatomic) _UIFocusFastScrollingIndexBarView *indexBarView; // @synthesize indexBarView=_indexBarView;
@property(copy, nonatomic) NSArray *indexEntries; // @synthesize indexEntries=_indexEntries;
- (void)_updateIndexBarIndicator;	// IMP=0x0000000000750177
- (void)_buttonScrollDelayEnded;	// IMP=0x000000000075014a
- (_Bool)_cancelButtonScrollDelay;	// IMP=0x00000000007500e2
- (void)_beginButtonScrollDelayWithDuration:(double)arg1;	// IMP=0x0000000000750020
- (void)_cooldownEnded;	// IMP=0x000000000074fff3
- (void)_cancelCooldown;	// IMP=0x000000000074ffb0
- (void)_beginCooldownWithDuration:(double)arg1;	// IMP=0x000000000074feee
- (void)_stopTrackingMode;	// IMP=0x000000000074fea3
- (void)_startTrackingModeIfNecessary;	// IMP=0x000000000074fe58
- (_Bool)_canFastScrollWithStyle:(long long)arg1;	// IMP=0x000000000074fd5b
- (void)_finishDecelerating;	// IMP=0x000000000074fd0c
- (void)_attemptToStopDueToExternalEvent:(_Bool)arg1;	// IMP=0x000000000074fbca
- (void)_stopDueToExternalEvent;	// IMP=0x000000000074fba8
- (void)_attemptToStopIfInitiatedByGesture;	// IMP=0x000000000074fb88
- (void)_start;	// IMP=0x000000000074f8f7
- (void)_configureWithRequest:(id)arg1;	// IMP=0x000000000074f6eb
- (void)_hideDestinationIndicators;	// IMP=0x000000000074f6c1
- (void)_showDestinationIndicators;	// IMP=0x000000000074f697
- (void)_updateSoftFocusForVelocity:(CDStruct_c3b9c2ee)arg1;	// IMP=0x000000000074f537
- (void)_stopScrollingAnimation;	// IMP=0x000000000074f4d3
- (void)_setContentOffset:(struct CGPoint)arg1 withVelocity:(CDStruct_c3b9c2ee)arg2;	// IMP=0x000000000074f478
- (CDStruct_c3b9c2ee)_currentScrollViewDecelerationVelocity;	// IMP=0x000000000074f42c
- (void)_startScrollingAnimationWithVelocity:(CDStruct_c3b9c2ee)arg1 friction:(struct CGPoint)arg2;	// IMP=0x000000000074ef5d
- (void)_handleAnimationGroupScrollingCompletionWithInitialVelocity:(struct CGPoint)arg1 bounces:(_Bool)arg2;	// IMP=0x000000000074ec66
- (void)_handleAnimationGroupScrollingAnimations;	// IMP=0x000000000074eb30
- (void)_endDiscreteButtonScrollGesture;	// IMP=0x000000000074ead3
- (void)_discreteButtonScrollHeartbeat:(id)arg1;	// IMP=0x000000000074e873
- (long long)_nextDiscretePageScrollIndexFromIndex:(long long)arg1 inDirection:(double)arg2;	// IMP=0x000000000074e5c6
- (long long)_nextDiscretePageScrollIndexFromIndex:(long long)arg1 forHeading:(unsigned long long)arg2;	// IMP=0x000000000074e595
- (void)_stopDiscreteButtonScrollDisplayLink;	// IMP=0x000000000074e4f8
- (void)_startDiscreteButtonScrollDisplayLink;	// IMP=0x000000000074e42d
- (void)_advanceToNextContentOffsetPageAlongHeading:(unsigned long long)arg1;	// IMP=0x000000000074e262
- (long long)_advanceToNextEntryFromIndex:(long long)arg1 alongHeading:(unsigned long long)arg2;	// IMP=0x000000000074e06a
- (void)_startDiscreteButtonScrollGestureAlongHeading:(unsigned long long)arg1;	// IMP=0x000000000074df47
- (_Bool)_shouldArrowButtonInterruptPanGesture;	// IMP=0x000000000074defa
- (_Bool)_shouldArrowButtonGestureDiscreteScroll;	// IMP=0x000000000074deb4
- (void)_handlePageButtonGesture:(id)arg1;	// IMP=0x000000000074dd57
- (void)_handleJoystickGesture:(id)arg1;	// IMP=0x000000000074dac9
- (void)_resetAllButtonGestures;	// IMP=0x000000000074da6c
- (void)_beginDeceleratingAfterContinuousButtonScroll;	// IMP=0x000000000074d9e5
- (void)_continuousButtonScrollHeartbeat:(id)arg1;	// IMP=0x000000000074d641
- (void)_stopContinuousButtonScrollDisplayLink;	// IMP=0x000000000074d5a4
- (void)_startContinuousButtonScrollDisplayLink;	// IMP=0x000000000074d4c0
- (void)_startContinuousButtonScrollAlongHeading:(unsigned long long)arg1 withVelocity:(CDStruct_c3b9c2ee)arg2 delayed:(_Bool)arg3;	// IMP=0x000000000074d42e
- (_Bool)_shouldArrowButtonGestureInstantlyAdvanceToNextEntry;	// IMP=0x000000000074d3b6
- (void)_handleArrowButtonGesture:(id)arg1;	// IMP=0x000000000074d0df
- (void)_rotaryHeartbeat:(id)arg1;	// IMP=0x000000000074cd0d
- (CDStruct_c3b9c2ee)_velocityOfRotaryGesture:(id)arg1 inView:(id)arg2;	// IMP=0x000000000074cc80
- (struct CGPoint)_translationOfRotaryGesture:(id)arg1 inView:(id)arg2;	// IMP=0x000000000074cbb5
- (void)_handleRotaryEnd:(id)arg1;	// IMP=0x000000000074cb59
- (struct CGPoint)_rotaryRubberbandedOffsetForTranslatedOffset:(struct CGPoint)arg1;	// IMP=0x000000000074c8c2
- (struct CGPoint)_rotaryTranslatedOffsetForCurrentOffset:(struct CGPoint)arg1 translation:(struct CGPoint)arg2;	// IMP=0x000000000074c89b
- (void)_updateRotaryAcceleration:(id)arg1;	// IMP=0x000000000074c627
- (void)_handleRotaryChanged:(id)arg1;	// IMP=0x000000000074c476
- (_Bool)_updateRotaryDirection:(id)arg1;	// IMP=0x000000000074c3ea
- (void)_handleRotaryBegin:(id)arg1;	// IMP=0x000000000074c129
- (void)_handleCommonRotaryBegin:(id)arg1;	// IMP=0x000000000074c0ee
- (void)_handleRotaryGesture:(id)arg1;	// IMP=0x000000000074c034
- (void)_resetPanDeadBand;	// IMP=0x000000000074bf91
- (_Bool)_isPanDeadBandActive;	// IMP=0x000000000074bf20
- (struct CGPoint)_applyPanDeadbandToTranslation:(struct CGPoint)arg1 withVelocity:(CDStruct_c3b9c2ee)arg2 inScrollView:(id)arg3;	// IMP=0x000000000074bc67
- (void)_resetSwipeAcceleration;	// IMP=0x000000000074bc41
- (void)_endDraggingWithFinalVelocity:(CDStruct_c3b9c2ee)arg1;	// IMP=0x000000000074b474
- (void)_beginInitialSwipeDeceleration;	// IMP=0x000000000074b42b
- (void)_handleSwipePanEnd:(id)arg1;	// IMP=0x000000000074b3ca
- (void)_handleSwipePanChanged:(id)arg1;	// IMP=0x000000000074aead
- (void)_handleSwipePanBegin:(id)arg1;	// IMP=0x000000000074adaa
- (_Bool)_canFastScrollWithEdgeSwipe;	// IMP=0x000000000074ad42
- (void)_interpretDigitzerLocation:(struct CGPoint)arg1 toFindEntryIndex:(long long *)arg2 deflection:(double *)arg3;	// IMP=0x000000000074ab76
- (void)_updateEdgeGesture;	// IMP=0x000000000074aa95
- (void)_startEdgeGesture;	// IMP=0x000000000074a9b8
- (void)_handleEdgePanEnd:(id)arg1;	// IMP=0x000000000074a964
- (void)_handleEdgePanChanged:(id)arg1;	// IMP=0x000000000074a952
- (void)_handleEdgePanBegin:(id)arg1;	// IMP=0x000000000074a940
- (void)_handlePanEnd:(id)arg1;	// IMP=0x000000000074a8ec
- (void)_handlePanChanged:(id)arg1;	// IMP=0x000000000074a898
- (long long)_panFastScrollStyleFromGesture:(id)arg1;	// IMP=0x000000000074a7fc
- (void)_handlePanBegin:(id)arg1 withStyle:(long long)arg2;	// IMP=0x000000000074a772
- (void)_handlePanGesture:(id)arg1;	// IMP=0x000000000074a6a9
- (long long)indexOfEntryNearestToScrollViewBounds:(struct CGRect)arg1 inDisplayedEntries:(id)arg2;	// IMP=0x000000000074a61c
- (unsigned long long)currentHeading;	// IMP=0x000000000074a475
@property(readonly, nonatomic) struct CGPoint initialContentOffset;
@property(readonly, nonatomic) _UIFocusFastScrollingIndexBarEntry *focusDestinationEntry;
@property(readonly, nonatomic) long long userScrollingStyle;
@property(readonly, nonatomic) long long scrollingStyle;
@property(readonly, nonatomic, getter=isScrollingY) _Bool scrollingY;
@property(readonly, nonatomic, getter=isScrollingX) _Bool scrollingX;
@property(readonly, nonatomic, getter=isDecelerating) _Bool decelerating;
@property(readonly, nonatomic, getter=isDragging) _Bool dragging;
- (void)stop;	// IMP=0x000000000074a2c3
- (void)start;	// IMP=0x000000000074a2b1
@property(readonly, nonatomic) __weak UIScrollView *scrollView;
- (id)initWithRequest:(id)arg1;	// IMP=0x000000000074a107

@end

