//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/NSObject-Protocol.h>

@class _UIFocusFastScrollingIndexBarView;

@protocol _UIFocusFastScrollingIndexBarViewDelegate <NSObject>
- (void)focusFastScrollingIndexBarViewSelectTriggered:(_UIFocusFastScrollingIndexBarView *)arg1;
@end

