//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMapTable, NSString, NSTimer;

__attribute__((visibility("hidden")))
@interface _UIFocusActiveSceneObserver_Classic
{
    NSMapTable *_hidObserverMapTable;	// 16 = 0x10
    struct {
        unsigned int supportsHIDUpdates:1;
    } _flags;	// 24 = 0x18
    NSTimer *_inactiveSceneObserverTimer;	// 32 = 0x20
    long long _inactiveSceneObserverTimerFireCount;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00000000001f18c8
- (id)descriptionBuilder;	// IMP=0x00000000001f17e7
- (void)_keyWindowDidChangeNotification:(id)arg1;	// IMP=0x00000000001f1628
- (void)_screenUUIDDidChangeNotification:(id)arg1;	// IMP=0x00000000001f123b
- (void)observerDeliveryPolicyDidChange:(id)arg1;	// IMP=0x00000000001f107c
- (void)_windowDidDetachContext:(id)arg1;	// IMP=0x00000000001f0ffe
- (void)_windowDidAttachContext:(id)arg1;	// IMP=0x00000000001f0f80
- (void)_removeDeliverObserverForWindow:(id)arg1;	// IMP=0x00000000001f0ee5
- (id)_resolvedDisplayForWindow:(id)arg1;	// IMP=0x00000000001f0e36
- (void)_addDeliveryObserverForWindow:(id)arg1;	// IMP=0x00000000001f0c5b
- (_Bool)isActive;	// IMP=0x00000000001f09eb
- (void)dealloc;	// IMP=0x00000000001f07b5
- (void)stopMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x00000000001f06bf
- (void)beginMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x00000000001f05bb
- (void)_fireInactiveFocusObserver:(id)arg1;	// IMP=0x00000000001f007f
- (id)_initWithScene:(id)arg1;	// IMP=0x00000000001efdfd

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

