//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusActiveSceneObserver_KeyboardEventDeferring
{
}

- (_Bool)isActive;	// IMP=0x00000000001efdc3
- (void)_activeStateChanged:(id)arg1;	// IMP=0x00000000001efdb1
- (void)dealloc;	// IMP=0x00000000001efccd
- (id)_initWithScene:(id)arg1;	// IMP=0x00000000001efbc8

@end

