//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusUpdateReportFormatter
{
}

- (id)_bodyForReport:(id)arg1;	// IMP=0x00000000006f8489
- (id)_headerForReport:(id)arg1;	// IMP=0x00000000006f8152
- (id)stringFromReport:(id)arg1;	// IMP=0x00000000006f805e
- (id)_componentsFromReport:(id)arg1;	// IMP=0x00000000006f7f27

@end

