//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CADisplayLink, NSMapTable, NSTimer, UIScreen, _UIFocusEngineScrollableContainerOffsets;

__attribute__((visibility("hidden")))
@interface _UIFocusDisplayLinkScrollAnimator : NSObject
{
    UIScreen *_screen;	// 8 = 0x8
    _UIFocusEngineScrollableContainerOffsets *_singleScrollableContainerEntry;	// 16 = 0x10
    NSMapTable *_scrollableContainers;	// 24 = 0x18
    CADisplayLink *_displayLink;	// 32 = 0x20
    NSTimer *_timer;	// 40 = 0x28
    double _lastHeartbeatTime;	// 48 = 0x30
    double _defaultConvergenceRate;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000000075fbce
- (struct CGPoint)_hyperJumpContentOffsetIfNecessaryForEntry:(id)arg1 currentOffset:(struct CGPoint)arg2;	// IMP=0x000000000075fa0f
- (struct CGPoint)_applyAccelerationLimitToAcceleration:(struct CGPoint)arg1 currentOffset:(struct CGPoint)arg2 targetOffset:(struct CGPoint)arg3;	// IMP=0x000000000075f928
- (void)_processEntry:(id)arg1 timeDelta:(long long)arg2 completed:(id)arg3 cancelled:(id)arg4;	// IMP=0x000000000075f2a9
- (void)_removeEntry:(id)arg1;	// IMP=0x000000000075eef1
- (void)_commonHeartbeat:(double)arg1;	// IMP=0x000000000075e925
- (void)_commonHeartbeat;	// IMP=0x000000000075e8ec
- (void)_displayLinkHeartbeat:(id)arg1;	// IMP=0x000000000075e851
- (void)_timerHeartbeat:(id)arg1;	// IMP=0x000000000075e83f
- (_Bool)_shouldPushAndPopRunLoopModes;	// IMP=0x000000000075e82b
- (void)_updateHeartbeatConfiguration;	// IMP=0x000000000075e577
- (void)_switchToTimerScrolling;	// IMP=0x000000000075e4c6
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000000075e442
- (_Bool)_canCreateDisplayLink;	// IMP=0x000000000075e3e0
- (id)_createEntryForEnvironmentScrollableContainer:(id)arg1;	// IMP=0x000000000075df73
- (id)_entryForEnvironmentScrollableContainer:(id)arg1 createIfNeeded:(_Bool)arg2;	// IMP=0x000000000075dcee
- (id)_entryForScrollableContainer:(id)arg1;	// IMP=0x000000000075dc28
- (struct CGPoint)velocityToScrollFromOffset:(struct CGPoint)arg1 toOffset:(struct CGPoint)arg2;	// IMP=0x000000000075dba8
- (struct CGPoint)currentVelocityForScrollableContainer:(id)arg1;	// IMP=0x000000000075dabb
- (struct CGPoint)targetContentOffsetForScrollableContainer:(id)arg1;	// IMP=0x000000000075da45
- (_Bool)isAnimatingScrollableContainer:(id)arg1;	// IMP=0x000000000075da12
- (void)adjustTargetContentOffsetForScrollableContainer:(id)arg1 byDelta:(struct CGPoint)arg2;	// IMP=0x000000000075d980
- (void)cancelScrollingForScrollableContainer:(id)arg1;	// IMP=0x000000000075d8cc
- (void)setTargetContentOffset:(struct CGPoint)arg1 forEnvironmentScrollableContainer:(id)arg2 convergenceRate:(double)arg3 completion:(CDUnknownBlockType)arg4;	// IMP=0x000000000075d6ab
@property(nonatomic) double defaultConvergenceRate;
- (void)dealloc;	// IMP=0x000000000075d60b
- (id)initWithScreen:(id)arg1;	// IMP=0x000000000075d54f

@end

