//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIGestureRecognizer.h"

@class NSMutableOrderedSet, NSString, _UIRepeatingGestureClock;

__attribute__((visibility("hidden")))
@interface _UIFocusMovementPressGestureRecognizer : UIGestureRecognizer
{
    _Bool _shouldRepeat;	// 16 = 0x10
    unsigned long long _focusHeading;	// 24 = 0x18
    long long _repeatCount;	// 32 = 0x20
    _UIRepeatingGestureClock *_repeatingClock;	// 40 = 0x28
    NSMutableOrderedSet *_trackedPresses;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000000d1826e
@property(retain, nonatomic, getter=_trackedPresses, setter=_setTrackedPresses:) NSMutableOrderedSet *trackedPresses; // @synthesize trackedPresses=_trackedPresses;
@property(retain, nonatomic) _UIRepeatingGestureClock *repeatingClock; // @synthesize repeatingClock=_repeatingClock;
@property(nonatomic) long long repeatCount; // @synthesize repeatCount=_repeatCount;
@property(nonatomic) _Bool shouldRepeat; // @synthesize shouldRepeat=_shouldRepeat;
@property(nonatomic) unsigned long long focusHeading; // @synthesize focusHeading=_focusHeading;
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000d181db
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000d181c4
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000d181ad
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000000d18199
- (void)_updateForPresses:(id)arg1 action:(unsigned long long)arg2;	// IMP=0x0000000000d18074
- (void)_verifyTrackingPresses:(id)arg1;	// IMP=0x0000000000d17e6e
- (void)_stopTrackingPresses:(id)arg1;	// IMP=0x0000000000d17e05
- (void)_startTrackingPresses:(id)arg1;	// IMP=0x0000000000d17d9c
- (unsigned long long)focusHeadingForPresses:(id)arg1;	// IMP=0x0000000000d17d94
- (void)repeatingGestureClockDidTick:(id)arg1;	// IMP=0x0000000000d17aac
- (void)reset;	// IMP=0x0000000000d177d0
- (void)setFocusHeading:(unsigned long long)arg1 omitStateUpdate:(_Bool)arg2;	// IMP=0x0000000000d17504
- (_Bool)shouldReceiveEvent:(id)arg1;	// IMP=0x0000000000d174d3
- (void)setAllowedTouchTypes:(id)arg1;	// IMP=0x0000000000d17404
@property(readonly, nonatomic, getter=_isRecognizing) _Bool isRecognizing;
- (void)configureDefaults;	// IMP=0x0000000000d173a0
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x0000000000d172e3
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000000d17226

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

