//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CADisplayLink, NSArray, NSMapTable, NSSet, NSString, NSTimer, UIMoveEvent, UIScrollView, UIView, _UIFocusEffectsController, _UIFocusFastScrollingRecognizer, _UIFocusItemInfo, _UIFocusLinearMovementDebugView, _UIFocusMovementInfo, _UIFocusRotaryIndicatorView;
@protocol _UIFocusEventRecognizerDelegate;

__attribute__((visibility("hidden")))
@interface _UIFocusEventRecognizer : NSObject
{
    NSMapTable *_gestureRecognizers;	// 8 = 0x8
    _UIFocusRotaryIndicatorView *_rotaryIndicatorView;	// 16 = 0x10
    NSTimer *_showRotaryIndicatorAfterDelayTimer;	// 24 = 0x18
    double _panDeadBand;	// 32 = 0x20
    _UIFocusLinearMovementDebugView *_linearDebugView;	// 40 = 0x28
    struct CGPoint _touchBeganPoint;	// 48 = 0x30
    struct CGPoint _lastKnownTouchPoint;	// 64 = 0x40
    struct CGPoint _previousPoints[5];	// 80 = 0x50
    int _numFrames;	// 160 = 0xa0
    struct CGVector _progressAccumulator;	// 168 = 0xa8
    struct CGVector _unlockedAccumulator;	// 184 = 0xb8
    double _lastButtonPressTime;	// 200 = 0xc8
    unsigned long long _failedContinuousMovementHeading;	// 208 = 0xd0
    double _failedContinuousMovementTime;	// 216 = 0xd8
    _UIFocusFastScrollingRecognizer *_fastScrollingRecognizer;	// 224 = 0xe0
    unsigned long long _allowedFocusHeadingsDuringFastScrolling;	// 232 = 0xe8
    struct CGPoint _firstMomentumTouchPoint;	// 240 = 0xf0
    struct CGPoint _lastMomentumTouchPoint;	// 256 = 0x100
    struct CGPoint _momentumVelocity;	// 272 = 0x110
    double _momentumFriction;	// 288 = 0x120
    unsigned long long _focusUpdateCountSinceLastContinuousMovementBegan;	// 296 = 0x128
    CADisplayLink *_momentumDisplayLink;	// 304 = 0x130
    NSTimer *_joystickModeExitTimer;	// 312 = 0x138
    NSTimer *_joystickModeRepeatTimer;	// 320 = 0x140
    double _previousJoystickFocusMovementTime;	// 328 = 0x148
    double _previousJoystickRegionEntryTime;	// 336 = 0x150
    unsigned long long _joystickRepeatingHeading;	// 344 = 0x158
    CADisplayLink *_joystickFocusDirectionDisplayLink;	// 352 = 0x160
    _UIFocusMovementInfo *_previousJoystickFocusMovementInfo;	// 360 = 0x168
    long long _joystickRepeatCount;	// 368 = 0x170
    UIScrollView *_lastScrolledScroll;	// 376 = 0x178
    double _lastEdgeScrollEdgeValue;	// 384 = 0x180
    unsigned long long _inputType;	// 392 = 0x188
    _UIFocusItemInfo *_cachedFocusItemInfo;	// 400 = 0x190
    struct {
        unsigned int isEligibleToCrossSpeedBump:1;
        unsigned int isContinuingTouchWithMomentum:1;
        unsigned int isPerformingJoystickRollback:1;
        unsigned int isJoystickInRepeatMode:1;
        unsigned int isPendingJoystickRepeat:1;
        unsigned int isFastScrolling:1;
        unsigned int shouldApplyAcceleration:1;
        unsigned int shouldSupressActiveIndirectMotionUpdates:1;
        unsigned int startDeferingFocusOnTapHoldEnded:1;
    } _flags;	// 408 = 0x198
    _Bool _enabled;	// 412 = 0x19c
    _Bool _supportsFastScrolling;	// 413 = 0x19d
    UIView *_owningView;	// 416 = 0x1a0
    NSArray *_keyCommands;	// 424 = 0x1a8
    id <_UIFocusEventRecognizerDelegate> _delegate;	// 432 = 0x1b0
    UIMoveEvent *_moveEvent;	// 440 = 0x1b8
    _UIFocusEffectsController *_motionEffectsController;	// 448 = 0x1c0
}

+ (_Bool)_canSupportFastScrolling;	// IMP=0x0010000000704e12
- (void).cxx_destruct;	// IMP=0x00000000007055f3
@property(readonly, nonatomic, getter=_motionEffectsController) _UIFocusEffectsController *motionEffectsController; // @synthesize motionEffectsController=_motionEffectsController;
@property(retain, nonatomic, getter=_moveEvent, setter=_setMoveEvent:) UIMoveEvent *moveEvent; // @synthesize moveEvent=_moveEvent;
@property(nonatomic) __weak id <_UIFocusEventRecognizerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool supportsFastScrolling; // @synthesize supportsFastScrolling=_supportsFastScrolling;
@property(readonly, nonatomic) NSArray *keyCommands; // @synthesize keyCommands=_keyCommands;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) __weak UIView *owningView; // @synthesize owningView=_owningView;
- (void)_uiktest_handlePanGesture:(id)arg1;	// IMP=0x000000000070553c
- (id)_uiktest_panGestureRecognizer;	// IMP=0x0000000000705525
- (void)_uiktest_setPanGestureRecognizer:(id)arg1;	// IMP=0x000000000070550e
- (void)_sendGestureBeginNotification;	// IMP=0x00000000007054ae
- (_Bool)_isRotaryFastScrolling;	// IMP=0x000000000070542e
- (void)_fastScrollingEnded;	// IMP=0x00000000007053f3
- (void)_fastScrollingBeganInScrollView:(id)arg1 initiationMode:(long long)arg2;	// IMP=0x000000000070534c
- (void)fastScrollingRecognizer:(id)arg1 didRecognizeFastScrollingRequest:(id)arg2;	// IMP=0x0000000000704f67
- (void)_createFastScrollingRecognizerIfNeeded;	// IMP=0x0000000000704e90
- (void)_setSupportsFastScrolling:(_Bool)arg1;	// IMP=0x0000000000704e4e
@property(readonly, nonatomic, getter=_fastScrollingRecognizer) _UIFocusFastScrollingRecognizer *fastScrollingRecognizer;
- (void)_sendMomentumEndNotificationsAndAnimateRollback:(_Bool)arg1;	// IMP=0x0000000000704dcf
- (void)_stopMomentumAndPerformRollback;	// IMP=0x0000000000704d7d
- (_Bool)_shouldPerformFocusUpdateWithCurrentMomentumStatus;	// IMP=0x0000000000704d04
- (void)_momentumHeartbeat:(id)arg1;	// IMP=0x0000000000704a0f
- (unsigned long long)_momentumFocusHeadingForAccumulator:(struct CGVector)arg1;	// IMP=0x00000000007049b6
- (void)_beginMomentumImmediatelyWithVelocity:(struct CGPoint)arg1 friction:(double)arg2;	// IMP=0x0000000000704891
- (void)_continueTouchWithMomentum;	// IMP=0x0000000000704582
- (void)_recordMomentumForPoint:(struct CGPoint)arg1 reportedVelocity:(struct CGPoint)arg2;	// IMP=0x0000000000704500
- (void)_resetMomentum;	// IMP=0x000000000070449a
- (struct CGSize)_momentumReferenceSize;	// IMP=0x0000000000704310
- (void)_resetMotionEffects;	// IMP=0x00000000007042f7
- (void)_resetJoystick;	// IMP=0x0000000000704250
- (void)_joystickDisplayLinkHeartbeat:(id)arg1;	// IMP=0x0000000000703fd9
- (unsigned long long)_headingForJoystickPosition:(struct CGPoint)arg1 usingMinimumRadius:(double)arg2;	// IMP=0x0000000000703f49
- (struct CGVector)_joystickVelocityForHeading:(unsigned long long)arg1;	// IMP=0x0000000000703f19
- (id)_focusMovementForJoystickPosition:(struct CGPoint)arg1 usingMinimumRadius:(double)arg2 focusMovementStyle:(long long)arg3;	// IMP=0x0000000000703dc6
- (_Bool)_joystickFocusMovement:(id)arg1 shouldBeConsideredEqualToFocusMovement:(id)arg2;	// IMP=0x0000000000703cb4
- (double)_joystickRepeatDurationForTimeInMovementZone:(double)arg1;	// IMP=0x0000000000703ae7
- (void)_joystickPerformRepeat:(id)arg1;	// IMP=0x0000000000703ada
- (_Bool)_joystickAttemptFocusMovementWithRequest:(id)arg1;	// IMP=0x0000000000703a32
- (void)_handleJoystickTiltMode:(id)arg1;	// IMP=0x0000000000703663
- (void)_handleJoystickRepeatMode:(id)arg1;	// IMP=0x00000000007032ab
- (void)_exitJoystickModeForReal:(id)arg1;	// IMP=0x0000000000703264
- (void)_joystickGestureEnded:(id)arg1;	// IMP=0x0000000000703126
- (void)_joystickGestureUpdated:(id)arg1;	// IMP=0x00000000007030fd
- (void)_joystickGestureBegan:(id)arg1;	// IMP=0x0000000000702f9d
- (void)_resetFailedMovementHeading;	// IMP=0x0000000000702f89
- (void)_resetContinuousMovementState;	// IMP=0x0000000000702f71
- (void)_resetProgressAccumulatorWithHeading:(unsigned long long)arg1;	// IMP=0x0000000000702e8d
- (void)_panGestureCancelled:(id)arg1;	// IMP=0x0000000000702e5b
- (void)_panGestureEnd:(id)arg1;	// IMP=0x0000000000702e26
- (void)_cleanupPanMomentumWithAccumulator:(struct CGVector)arg1 movementSuccess:(_Bool)arg2;	// IMP=0x0000000000702de4
- (_Bool)_hasFailedMovementHeadingExpired;	// IMP=0x0000000000702d86
- (void)_updateFailedContinuousMovementHeading:(unsigned long long)arg1;	// IMP=0x0000000000702d20
- (void)_continuousMovementFailedWithPrimaryHeading:(unsigned long long)arg1;	// IMP=0x0000000000702ca3
- (void)_continuousMovementSucceededWithDirectionalHeading:(unsigned long long)arg1;	// IMP=0x0000000000702bc5
- (_Bool)_attemptToRecognizeContinuousMovementRequest:(id)arg1;	// IMP=0x0000000000702b1a
- (id)_createMovementInfoForHeading:(unsigned long long)arg1 groupFilter:(long long)arg2 acceleratedVelocity:(struct CGPoint)arg3;	// IMP=0x0000000000702a91
- (_Bool)_attemptPanFocusMovementWithHeading:(unsigned long long)arg1 acceleratedVelocity:(struct CGPoint)arg2 focusSystem:(id)arg3 studyLogData:(id)arg4;	// IMP=0x0000000000702961
- (unsigned long long)_calculateDirectionalHeadingForAccumulator:(struct CGVector)arg1 studyLogData:(id)arg2;	// IMP=0x00000000007028ec
- (void)_updateMotionEffectsControllerWithProgressAccumulator:(struct CGVector)arg1 unlockedAccumulator:(struct CGVector)arg2;	// IMP=0x00000000007028b1
- (void)_updateAccumulatorsWithScaledDelta:(struct CGPoint)arg1 unlockedDelta:(struct CGPoint)arg2 studyLogData:(id)arg3;	// IMP=0x000000000070287b
- (struct CGVector)_accelerationFactorForCurrentVelocity:(struct CGPoint)arg1 alpha:(double)arg2 isRotaryGesture:(_Bool)arg3 isFocusInKeyboard:(_Bool)arg4 remoteTouchSurfaceType:(unsigned long long)arg5;	// IMP=0x00000000007025b8
- (struct CGPoint)_applyButtonMaskTimeToValue:(struct CGPoint)arg1 remoteTouchSurfaceType:(unsigned long long)arg2;	// IMP=0x0000000000702578
- (struct CGPoint)_applyAxisLockingForNormalizedPoint:(struct CGPoint)arg1 toDelta:(struct CGPoint)arg2;	// IMP=0x0000000000702461
- (struct CGPoint)_applyHorizontalFlipForFocusItemInfo:(id)arg1 toDelta:(struct CGPoint)arg2;	// IMP=0x0000000000702420
- (struct CGPoint)_applyPanDeadbandToValue:(struct CGPoint)arg1 startPoint:(struct CGPoint)arg2 currentPoint:(struct CGPoint)arg3 remoteTouchSurfaceType:(unsigned long long)arg4;	// IMP=0x00000000007022db
- (struct CGPoint)_calculateDeltaForNormalizedPoint:(struct CGPoint)arg1 studyLogData:(id)arg2;	// IMP=0x00000000007022b2
- (id)_createStudyLogDataForPanNormalizedPoint:(struct CGPoint)arg1 reportedVelocity:(struct CGPoint)arg2;	// IMP=0x00000000007022aa
- (id)_createPanMovementRequestWithFocusSystem:(id)arg1;	// IMP=0x0000000000702205
- (void)_updatePanLocation:(struct CGPoint)arg1 reportedVelocity:(struct CGPoint)arg2 remoteTouchSurfaceType:(unsigned long long)arg3;	// IMP=0x0000000000701cb8
- (void)_panGestureStart:(id)arg1;	// IMP=0x0000000000701bb6
- (_Bool)focusEnginePanGestureRecognizerShouldRecognizeImmediately:(id)arg1;	// IMP=0x0000000000701ba6
- (void)_resetPanDeadband;	// IMP=0x0000000000701b61
- (_Bool)_attemptRotaryFocusMovementWithLinearHeading:(unsigned long long)arg1 directionalHeading:(unsigned long long)arg2 focusMovementAxis:(long long)arg3 focusSystem:(id)arg4 acceleratedVelocity:(struct CGPoint)arg5 studyLogData:(id)arg6;	// IMP=0x0000000000701a31
- (unsigned long long)_calculateLinearHeadingForAccumulator:(struct CGVector)arg1 studyLogData:(id)arg2;	// IMP=0x00000000007019e4
- (struct CGPoint)_pointForLinearValue:(double)arg1 axis:(unsigned long long)arg2;	// IMP=0x00000000007019c5
- (id)_createRotaryMovementRequestWithFocusSystem:(id)arg1;	// IMP=0x0000000000701920
- (id)_createStudyLogDataForRotaryDistance:(double)arg1 delta:(double)arg2 reportedVelocity:(double)arg3;	// IMP=0x0000000000701918
- (void)_updateRotaryDistance:(double)arg1 delta:(double)arg2 reportedVelocity:(double)arg3 remoteTouchSurfaceType:(unsigned long long)arg4 focusMovementAxis:(long long)arg5;	// IMP=0x00000000007013a9
- (void)_hideRotaryIndicator;	// IMP=0x0000000000701373
- (void)_showRotaryIndicator;	// IMP=0x00000000007012bd
- (void)_timerFiredForShowRotaryIndicator:(id)arg1;	// IMP=0x0000000000701243
- (void)_cancelShowRotaryIndicatorTimer;	// IMP=0x0000000000701211
- (void)_showRotaryIndicatorAfterDelay;	// IMP=0x000000000070114a
- (void)_handleRotaryCancelled:(id)arg1;	// IMP=0x000000000070110b
- (void)_handleRotaryEnd:(id)arg1;	// IMP=0x00000000007010b4
- (void)_handleRotaryBegin:(id)arg1;	// IMP=0x000000000070103b
- (void)_handleRotaryGesture:(id)arg1;	// IMP=0x0000000000700d83
- (void)_resetCachedFocusItemInfo;	// IMP=0x0000000000700d63
- (id)_retrieveCachedFocusItemInfo;	// IMP=0x0000000000700c94
- (void)_resetProgressAccumulator;	// IMP=0x0000000000700c7d
- (id)_globalCoordinateSpace;	// IMP=0x0000000000700c2d
- (id)_focusSystemSceneComponent;	// IMP=0x0000000000700b8c
- (_Bool)_canMoveFocusWithRotaryInputInFocusContext:(id)arg1;	// IMP=0x0000000000700af2
- (_Bool)_shouldAcceptInputType:(unsigned long long)arg1;	// IMP=0x000000000070089c
- (struct CGSize)_touchSensitivityForItem:(id)arg1 remoteTouchSurfaceType:(unsigned long long)arg2;	// IMP=0x0000000000700207
- (int)_touchRegionForDigitizerLocation:(struct CGPoint)arg1;	// IMP=0x00000000007000b7
- (_Bool)_buttonMaskTimeHasExpired;	// IMP=0x000000000070005f
- (id)currentFocusBehavior;	// IMP=0x0000000000700019
- (void)rotaryGestureRecognizerFailedClassifyingMovement:(id)arg1;	// IMP=0x0000000000700007
- (void)rotaryGestureRecognizerBeganClassifyingMovement:(id)arg1;	// IMP=0x00000000006fff06
- (void)_gestureRecognizerFailed:(id)arg1;	// IMP=0x00000000006ffe84
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;	// IMP=0x00000000006ffdd3
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;	// IMP=0x00000000006ffdc3
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;	// IMP=0x00000000006ffbba
- (_Bool)_hideLinearDebugOverlayIfNecessary:(_Bool)arg1;	// IMP=0x00000000006ffa54
- (void)_showLinearDebugOverlay:(_Bool)arg1;	// IMP=0x00000000006ff57e
- (void)_handleLinearDebugOverlayGesture:(id)arg1;	// IMP=0x00000000006ff4c2
- (void)_handleJoystickGesture:(id)arg1;	// IMP=0x00000000006ff415
- (void)_handleTapGesture:(id)arg1;	// IMP=0x00000000006ff30c
- (void)_handlePanGesture:(id)arg1;	// IMP=0x00000000006ff0e3
- (void)_handleTabulatorGesture:(id)arg1;	// IMP=0x00000000006fee0b
- (void)_handlePageButtonGesture:(id)arg1;	// IMP=0x00000000006febf0
- (void)_handleArrowButtonGesture:(id)arg1;	// IMP=0x00000000006fe8b8
- (void)_handleSelectObserverGesture:(id)arg1;	// IMP=0x00000000006fe809
- (void)_handleSelectGesture:(id)arg1;	// IMP=0x00000000006fe7cc
- (_Bool)_moveInDirection:(unsigned long long)arg1 groupFilter:(long long)arg2 withEvaluator:(CDUnknownBlockType)arg3;	// IMP=0x00000000006fe743
- (_Bool)_moveInDirection:(unsigned long long)arg1 groupFilter:(long long)arg2 withSearchInfo:(id)arg3;	// IMP=0x00000000006fe557
- (_Bool)_moveInDirection:(unsigned long long)arg1 groupFilter:(long long)arg2;	// IMP=0x00000000006fe542
- (_Bool)_moveWithEvent:(id)arg1;	// IMP=0x00000000006fe42f
- (_Bool)_didRecognizeFocusMovementRequest:(id)arg1;	// IMP=0x00000000006fe271
- (id)_focusMovementSystem;	// IMP=0x00000000006fe0e1
- (void)_focusSystemEnabledStateDidChange:(id)arg1;	// IMP=0x00000000006fe00c
- (void)_focusBehaviorDidChange:(id)arg1;	// IMP=0x00000000006fdff8
- (void)_focusDidUpdate:(id)arg1;	// IMP=0x00000000006fdfe6
@property(readonly, nonatomic) NSSet *gesturesForFailureRequirements;
- (void)_cancelAllGestureRecognizers;	// IMP=0x00000000006fde18
- (void)_updateGestureRecognizersForcingRemoval:(_Bool)arg1;	// IMP=0x00000000006fde04
- (void)_updateRotaryIndicatorView;	// IMP=0x00000000006fdcdc
- (void)_updateGestureRecognizersForcingRemoval:(_Bool)arg1 studyLogData:(id)arg2;	// IMP=0x00000000006fc514
- (id)gestureForName:(unsigned long long)arg1;	// IMP=0x00000000006fc4fe
- (void)setGesture:(id)arg1 forName:(unsigned long long)arg2;	// IMP=0x00000000006fc4d2
- (void)reset;	// IMP=0x00000000006fc442
- (void)dealloc;	// IMP=0x00000000006fc2e7
- (id)initWithOwningView:(id)arg1;	// IMP=0x00000000006fbebf
- (id)init;	// IMP=0x00000000006fbe38

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

