//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PrototypeTools/PTSettings.h>

@class _UIFocusDeferralSettings, _UIFocusHaloSettings;

__attribute__((visibility("hidden")))
@interface _UIFocusSettings : PTSettings
{
    _UIFocusDeferralSettings *_deferralSettings;	// 8 = 0x8
    _UIFocusHaloSettings *_haloSettings;	// 16 = 0x10
}

+ (id)settingsControllerModule;	// IMP=0x00600000010ef04c
- (void).cxx_destruct;	// IMP=0x00000000010ef2ba
@property(retain, nonatomic) _UIFocusHaloSettings *haloSettings; // @synthesize haloSettings=_haloSettings;
@property(retain, nonatomic) _UIFocusDeferralSettings *deferralSettings; // @synthesize deferralSettings=_deferralSettings;
- (void)setDefaultValues;	// IMP=0x00000000010ef01d

@end

