//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIScene;

__attribute__((visibility("hidden")))
@interface _UIFocusActiveSceneObserver
{
    UIScene *_scene;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000000001efbb7
- (void)stopMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x00000000001efbb1
- (void)beginMonitoringContextChangesForWindow:(id)arg1;	// IMP=0x00000000001efbab
- (id)_initWithScene:(id)arg1;	// IMP=0x00000000001efb68
- (id)initWithScene:(id)arg1;	// IMP=0x00000000001efa4f
- (id)init;	// IMP=0x00000000001efa3b

@end

