//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIFocusMovementDirectionalPressGestureRecognizer
{
    struct {
        unsigned int determinedPressSource:1;
    } _flags;	// 8 = 0x8
    unsigned long long _pressSource;	// 16 = 0x10
}

@property(nonatomic) unsigned long long pressSource; // @synthesize pressSource=_pressSource;
- (void)reset;	// IMP=0x0000000001046edf
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000001046e59
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000001046dd3
- (void)pressesChanged:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000001046d4d
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000000010469bc
- (id)_filterPressesByPressSource:(id)arg1;	// IMP=0x00000000010467d4
- (unsigned long long)focusHeadingForPresses:(id)arg1;	// IMP=0x0000000001046736
- (void)configureDefaults;	// IMP=0x00000000010466fc

@end

