//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIWindow.h"

@class NSArray, NSTimer, UIScrollView;

__attribute__((visibility("hidden")))
@interface _UIFocusDebugWindow : UIWindow
{
    NSTimer *_timer;	// 288 = 0x120
    NSArray *_cacheModules;	// 296 = 0x128
    UIScrollView *_scrollView;	// 304 = 0x130
    struct CGPoint _lastDragPoint;	// 312 = 0x138
}

+ (_Bool)_isSystemWindow;	// IMP=0x0060000000daf6f5
+ (_Bool)hasAnyModules;	// IMP=0x0060000000daf6ad
+ (id)moduleClasses;	// IMP=0x00600000009c75d9
- (void).cxx_destruct;	// IMP=0x0000000000db0541
- (void)_update:(id)arg1;	// IMP=0x0000000000db03e0
- (void)_updateTimer;	// IMP=0x0000000000db02fd
- (void)_searchForFocusRegionsInContext:(id)arg1;	// IMP=0x0000000000db02f7
- (_Bool)_isEligibleForFocusOcclusion;	// IMP=0x0000000000db02ef
- (_Bool)isTransparentFocusItem;	// IMP=0x0000000000db02e7
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x0000000000db01f5
- (void)setHidden:(_Bool)arg1;	// IMP=0x0000000000db01b4
- (void)drag:(id)arg1;	// IMP=0x0000000000db00a4
- (id)initWithWindowScene:(id)arg1;	// IMP=0x0000000000daf705
- (_Bool)canBecomeKeyWindow;	// IMP=0x0000000000daf6fd

@end

